<!doctype html>
<html><head><meta charset="utf-8"><style>
@page{margin:34px 42px 48px}body{font-family:DejaVu Sans,sans-serif;color:#10213b;font-size:10px;line-height:1.5}.header{border-bottom:3px solid #0969e8;padding-bottom:14px}.brand{font-size:25px;font-weight:bold;letter-spacing:.04em}.silver{color:#7d8795}.blue{color:#0969e8}.meta{float:right;text-align:right;margin-top:-34px}.clear{clear:both}.columns{width:100%;margin-top:22px}.columns td{width:50%;vertical-align:top}.label{color:#64748b;text-transform:uppercase;font-size:8px;letter-spacing:.08em}.items{width:100%;border-collapse:collapse;margin-top:24px}.items th,.items td{padding:8px;border-bottom:1px solid #dbe3ec;text-align:left}.items th{background:#f3f6fa}.right{text-align:right!important}.totals{width:42%;margin:18px 0 0 auto;border-collapse:collapse}.totals td{padding:5px}.total{border-top:2px solid #10213b;font-size:13px}.badge{display:inline-block;padding:4px 9px;background:#eaf2ff;color:#0759c8}.terms{margin-top:22px;padding-top:12px;border-top:1px solid #dbe3ec;white-space:pre-line}.footer{position:fixed;bottom:-30px;left:0;right:0;text-align:center;color:#64748b;font-size:8px}.page:after{content:counter(page)}
</style></head><body>
@php($business=$document->business_snapshot??[])
<div class="header"><div class="brand"><span class="silver">VIA</span><span class="blue">TECH</span></div><div>{{ $business['legal_name']??$business['name']??'ViaTech' }}</div><div class="meta"><strong>{{ strtoupper($type) }}</strong><br>{{ $document->number }}<br><span class="badge">{{ strtoupper($document->status) }}</span></div><div class="clear"></div></div>
<table class="columns"><tr><td><span class="label">Prepared for</span><br><strong>{{ $document->customer_name }}</strong><br>{{ $document->customer_company }}<br>{{ $document->customer_email }}<br>{{ $document->customer_phone }}</td><td class="right"><span class="label">Issue date</span><br>{{ $document->issue_date?->format('d M Y') }}<br><span class="label">{{ $type==='quotation'?'Valid until':'Due date' }}</span><br>{{ ($type==='quotation'?$document->expires_at:$document->due_date)?->format('d M Y') }}<br><span class="label">Currency</span><br>{{ $document->currency }}</td></tr></table>
<table class="items"><thead><tr><th>Description</th><th class="right">Qty</th><th class="right">Unit price</th><th class="right">Tax</th><th class="right">Amount</th></tr></thead><tbody>@foreach($document->items as $item)<tr><td>{{ $item->description }}</td><td class="right">{{ number_format($item->quantity,2) }}</td><td class="right">{{ number_format($item->unit_price,2) }}</td><td class="right">{{ number_format($item->tax_rate,2) }}%</td><td class="right">{{ number_format($item->total,2) }}</td></tr>@endforeach</tbody></table>
<table class="totals"><tr><td>Subtotal</td><td class="right">{{ $document->currency }} {{ number_format($document->subtotal,2) }}</td></tr><tr><td>Discount</td><td class="right">- {{ number_format($document->discount,2) }}</td></tr><tr><td>Tax</td><td class="right">{{ number_format($document->tax,2) }}</td></tr><tr class="total"><td><strong>Total</strong></td><td class="right"><strong>{{ $document->currency }} {{ number_format($document->total,2) }}</strong></td></tr>@if($type==='invoice')<tr><td>Paid</td><td class="right">{{ number_format($document->paid_amount,2) }}</td></tr><tr><td>Balance</td><td class="right"><strong>{{ number_format(max(0,$document->total-$document->paid_amount),2) }}</strong></td></tr>@endif</table>
@if($document->notes)<div class="terms"><strong>Notes</strong><br>{{ $document->notes }}</div>@endif
@if($document->terms)<div class="terms"><strong>Terms and conditions</strong><br>{{ $document->terms }}</div>@endif
<div class="footer">{{ $business['footer_text']??'ViaTech' }} · Page <span class="page"></span></div>
</body></html>
