<?php

$make = fn (string $group, string $title, string $intro, string $focus, string $delivery, array $highlights) => [
    'group'=>$group, 'title'=>$title, 'intro'=>$intro,
];

$pages = [
    'about-us'=>$make('Company','Practical technology, properly delivered','ViaTech helps organisations improve access, safety and daily operations with dependable technology and straightforward support.','We plan and supply integrated access, automation, parking, security and industrial site systems around real operating needs.','We review the site, recommend a sensible design and remain available after handover so the solution stays useful.',['Site-led planning','Clear proposals','Ongoing support']),
    'company-history'=>$make('Company','Built around real site requirements','Our progress has come from solving practical problems and building long-term customer relationships.','ViaTech began with dependable automation and security equipment, then grew into complete connected solutions through practical site experience.','We combine product knowledge, planning, installation coordination and support without adding unnecessary complexity.',['Practical experience','Trusted technology','Long-term service']),
    'core-values'=>$make('Company','The standards behind our work','Good technology matters, but the way it is selected, delivered and supported matters just as much.','We value clarity, responsibility and equipment that solves a genuine need. Recommendations should be honest and maintainable.','We explain scope and cost clearly, document important decisions and take ownership of the advice we provide.',['Be clear','Build responsibly','Support customers']),
    'our-team'=>$make('Company','People who understand the whole system','Our commercial, technical and support experience comes together in one coordinated customer response.','Sales and technical teams work from the same requirements, keeping proposals realistic through commissioning and handover.','We train users and provide a clear route for maintenance, changes and technical assistance after delivery.',['Consultation','Engineering','Customer support']),
    'brand-partners'=>$make('Company','Technology chosen for dependable results','We select established products according to the site, operating environment and support requirement.','Product quality, compatibility, spare-part availability and manufacturer support all matter more than a familiar name alone.','For multi-system projects, we define how compatible components work together to create a simpler operator experience.',['Proven equipment','Compatible systems','Supportable choices']),
    'our-brands'=>$make('Company','Specialist brands across our portfolio','Our portfolio brings together automation, access-control, safety and industrial products selected for different duties and budgets.','Product families include MOVE and DEFEND systems alongside established international manufacturers such as Powertech, Cuppon, eVACS, ZKTeco, WEJOIN, TAU, Ditec and LABEL.','Brand choice is made according to application, capacity, environment, integration needs and available technical support rather than name alone.',['Entry automation','Access and RFID','Physical security']),
    'certifications'=>$make('Company','Competence you can verify','Training, product knowledge and disciplined work help us deliver safer and more dependable systems.','Our team follows current product guidance and applies practical experience to configuration, installation and fault finding.','We document requirements, test before handover and provide relevant project records and certificates where required.',['Trained personnel','Documented testing','Professional handover']),
    'careers'=>$make('Company','Do useful work with a practical team','We welcome people who are curious about technology, careful in their work and comfortable solving real problems.','Our work suits engineers, technicians, coordinators and customer-focused professionals who value responsibility and learning.','Send your CV through our contact page with a short note about the work that interests you and the skills you bring.',['Learn continuously','Work responsibly','Help customers']),
    'latest-news'=>$make('Updates','Company and technology updates','Important ViaTech announcements, new capabilities and useful notes about the systems we support appear here.','We share service updates, project milestones and practical guidance when there is something genuinely useful to communicate.','For current availability or a project-specific question, contact us and we will connect you with the right person.',['Service notices','New capabilities','Practical guidance']),
    'solutions'=>$make('Solutions','Connected solutions for safer, smoother sites','We combine suitable products, clear operating logic and practical support around a specific site requirement.','Users, traffic, risks, peak periods and existing systems are considered before equipment is selected.','We can coordinate supply, configuration, installation and handover for a result that is manageable and expandable.',['Access and identity','Vehicle movement','Safety and security']),
    'loading-bay-solution'=>$make('Solutions','Safer, more efficient loading bays','Coordinate vehicle arrival, dock access and loading activity around the pace and risks of your site.','Signals, dock controls, barriers and status indicators help drivers and operators follow a safe sequence.','We define the operating sequence with your team before selecting interlocks, warnings and control equipment.',['Dock controls','Traffic indication','Safety interlocks']),
    'parking-management-guidance-solution'=>$make('Solutions','Make parking easier to find and manage','Guide drivers, understand occupancy and apply access rules without complicating the arrival experience.','Entry signs, space guidance and zone information reduce unnecessary circulation and can scale to space-level detection.','We can connect occupancy information, permissions and reporting for controlled or high-demand parking areas.',['Occupancy guidance','Entry control','Useful reporting']),
    'perimeter-security-solutions'=>$make('Solutions','Layered protection for the site boundary','A strong perimeter combines delay, detection and a clear response instead of relying on one device.','Entrances, vulnerable edges, lighting, movement and likely threats determine where protection or detection adds value.','We can link detection, cameras, gates and access events into a practical operator response.',['Physical protection','Early detection','Coordinated response']),
    'personnel-access-control-solution'=>$make('Solutions','Give the right people the right access','Manage who can enter specific areas, when they can enter and how activity is recorded.','Cards, mobile credentials or biometrics provide convenient entry while permissions remain centrally controlled.','We configure access groups, schedules and event records around staff, visitors and restricted areas.',['Flexible credentials','Time and area rules','Event records']),
    'rfid-etag-vehicle-access-control-solution'=>$make('Solutions','Fast, controlled vehicle access','Identify authorised vehicles automatically and reduce delays at busy gates or barriers.','RFID tags can be read as vehicles approach; reader position and lane layout are planned around real traffic.','Permissions can reflect vehicle, time or entrance, while exceptions are directed to an operator.',['Hands-free identification','Gate integration','Vehicle history']),
    'road-safety-solutions'=>$make('Solutions','Make internal roads safer to use','Use clear warnings, controlled speeds and better visibility where vehicles and people share a site.','Crossings, blind corners, loading areas, speed changes and vehicle routes reveal the hazards that need attention.','We combine appropriate signs, signals, detection, barriers and speed-management equipment with clear site rules.',['Hazard warnings','Traffic control','Pedestrian protection']),
    'visitor-management-solution'=>$make('Solutions','A professional welcome with better control','Register visitors, notify hosts and retain a useful record without creating unnecessary reception work.','Pre-registration speeds arrival, while check-in confirms details, required acknowledgements and badge information.','Current visitor lists, visit history and time-limited access support administration and emergency procedures.',['Pre-registration','Host notification','Visitor records']),
    'our-projects'=>$make('Projects','Solutions shaped by the site','Every project starts with a different need; our role is to turn it into a clear, supportable system.','We define scope, choose compatible equipment and coordinate delivery through testing and user handover.','Ask us for examples relevant to your sector, site type or technical requirement.',['Site assessment','Coordinated delivery','Tested handover']),
    'support'=>$make('Support','Help throughout the system life cycle','Get practical assistance with products, installed systems, maintenance needs and future changes.','Site details, product information, fault symptoms and photos help us understand an issue quickly.','Remote guidance, site assistance and preventive maintenance are available according to the system and need.',['Remote guidance','On-site assistance','Preventive maintenance']),
    'technical-support'=>$make('Support','Clear technical help when you need it','We help identify faults, confirm next steps and restore normal operation as efficiently as possible.','Note displayed messages, indicator states and recent changes, and keep model and installation details available.','We guide safe checks, then arrange remote action, parts or a site visit when required.',['Fault assessment','Remote checks','Escalation']),
    'warranty'=>$make('Support','Straightforward warranty assistance','We help establish product coverage and the appropriate route when supplied equipment develops a fault.','An invoice or project reference, product details, installation date and clear fault evidence help us assess coverage.','We explain applicable manufacturer terms before equipment is returned, repaired or replaced.',['Coverage check','Fault evidence','Clear next steps']),
    'product-demonstration'=>$make('Support','See how the solution works','A focused demonstration helps your team evaluate operation, usability and fit before making a decision.','Tell us the workflow you want to explore, who will attend and what the session needs to answer.','Afterwards we can clarify technical points, identify site considerations and prepare an appropriate proposal.',['Focused walkthrough','Questions answered','Clear next step']),
];

$pages['solutions']['details'] = [
    'title'=>'What a complete solution can include',
    'intro'=>'The final scope depends on the site. We combine only the elements needed to create one clear operating workflow.',
    'items'=>[
        ['title'=>'Identification and access','body'=>'RFID and smart-card readers, mobile credentials, biometric devices, intercoms and licence-plate recognition can identify people or vehicles before access is granted.'],
        ['title'=>'Physical control','body'=>'Doors, turnstiles, speed gates, boom barriers, automated gates, bollards and road blockers provide the physical control appropriate to the traffic and risk level.'],
        ['title'=>'Detection and awareness','body'=>'Vehicle loops, safety sensors, cameras, alarms, occupancy sensors and warning signals help the system understand conditions and alert operators to exceptions.'],
        ['title'=>'Software and integration','body'=>'Permissions, event histories, occupancy, visitor records and operational reports can be managed centrally and connected with compatible security or business systems.'],
    ],
    'applications'=>['Commercial buildings','Factories and warehouses','Housing communities','Hospitals and campuses','Retail and public parking','High-security facilities'],
    'process'=>[
        ['step'=>'01','title'=>'Understand','body'=>'Review traffic, users, risks, policies and existing infrastructure.'],
        ['step'=>'02','title'=>'Design','body'=>'Define the operating sequence, equipment, integrations and fallback modes.'],
        ['step'=>'03','title'=>'Deliver','body'=>'Coordinate installation, configuration and safe system integration.'],
        ['step'=>'04','title'=>'Handover','body'=>'Test real scenarios, train operators and document the completed system.'],
    ],
];

$pages['our-projects']['details'] = [
    'title'=>'The work behind a successful project',
    'intro'=>'A project is more than an equipment list. The result must fit the site, work during normal and exceptional conditions, and remain supportable.',
    'items'=>[
        ['title'=>'Vehicle entrance projects','body'=>'Controlled entrances for offices, factories and communities can combine barriers or gates with RFID, ANPR, intercoms, safety loops and visitor approval.'],
        ['title'=>'People and visitor access','body'=>'Door and turnstile projects can manage staff, contractors and visitors with suitable credentials, schedules, anti-passback rules and event records.'],
        ['title'=>'Parking and traffic projects','body'=>'Parking work may include entry and exit control, occupancy guidance, payment interfaces, traffic signals, lane equipment and management reporting.'],
        ['title'=>'Perimeter and industrial projects','body'=>'Higher-risk and industrial sites may require automated gates, bollards, blockers, detection, warnings, CCTV integration and carefully defined emergency operation.'],
    ],
    'applications'=>['Corporate offices','Industrial facilities','Residential developments','Education and healthcare','Retail and hospitality','Government and secure sites'],
    'process'=>[
        ['step'=>'01','title'=>'Survey','body'=>'Record layout, traffic, utilities, interfaces and operational constraints.'],
        ['step'=>'02','title'=>'Approve','body'=>'Confirm drawings, scope, equipment, responsibilities and project programme.'],
        ['step'=>'03','title'=>'Implement','body'=>'Install and configure in coordination with civil, electrical and IT work.'],
        ['step'=>'04','title'=>'Prove','body'=>'Test normal, failure and emergency scenarios before training and handover.'],
    ],
];

$pages['our-projects']['portfolio'] = [
    'sectors'=>['All','Armed forces','Commercial','Domestic','Educational','Housing society','Industrial'],
    'items'=>[
        ['name'=>'Model Town','sector'=>'Housing society','scope'=>'Controlled entrance and vehicle access works'],
        ['name'=>'DHA Head Office','sector'=>'Commercial','scope'=>'Entrance automation and access-control works'],
        ['name'=>'Atomic Energy','sector'=>'Armed forces','scope'=>'Controlled-access and physical-security works'],
        ['name'=>'Linde Pakistan','sector'=>'Industrial','scope'=>'Industrial entrance and automation works'],
        ['name'=>'Glass Door Automation','sector'=>'Commercial','scope'=>'Automatic pedestrian entrance installation'],
        ['name'=>'Linde Pakistan – Site Works','sector'=>'Industrial','scope'=>'Industrial door and controlled-entry works'],
        ['name'=>'Forman Christian College','sector'=>'Educational','scope'=>'Campus access and entrance automation'],
        ['name'=>'MM Tower','sector'=>'Commercial','scope'=>'Commercial building entrance automation'],
        ['name'=>'The Chenab Club','sector'=>'Commercial','scope'=>'Guest and controlled-entry works'],
        ['name'=>'Pak Arab Housing Society','sector'=>'Housing society','scope'=>'Residential vehicle-access controls'],
        ['name'=>'Swing Gate Automation','sector'=>'Domestic','scope'=>'Automated swing-gate installation'],
        ['name'=>'Okara Cantt','sector'=>'Armed forces','scope'=>'Secure entrance-control works'],
        ['name'=>'Fauji Fresh n Freeze','sector'=>'Industrial','scope'=>'Industrial access and loading-area works'],
        ['name'=>'Roshan Packages','sector'=>'Industrial','scope'=>'Industrial doors and entrance controls'],
        ['name'=>'University of Central Punjab','sector'=>'Educational','scope'=>'Campus entrance and access works'],
        ['name'=>'Motorized Aluminium Roller Shutter','sector'=>'Commercial','scope'=>'Motorized shutter supply and installation'],
        ['name'=>'Remote-Control Sliding Gate','sector'=>'Domestic','scope'=>'Residential sliding-gate automation'],
        ['name'=>'PAF Falcon Complex','sector'=>'Armed forces','scope'=>'Controlled vehicle-entrance works'],
        ['name'=>'Royal Orchard Multan','sector'=>'Housing society','scope'=>'Automatic road-barrier installation'],
        ['name'=>'Hermetic Door','sector'=>'Commercial','scope'=>'Specialist controlled-door installation'],
        ['name'=>'Industrial Doors and Gate Automation','sector'=>'Industrial','scope'=>'Heavy-duty entrance automation'],
        ['name'=>'Abdullah Gardens','sector'=>'Housing society','scope'=>'Community vehicle-access works'],
        ['name'=>'Novatex','sector'=>'Industrial','scope'=>'Industrial entry and door systems'],
    ],
];

$pages['about-us']['blocks'] = [
        ['type'=>'story','eyebrow'=>'ViaTech Technical Consultants','title'=>'A journey of purpose and practical engineering','body'=>['ViaTech works across automatic entrances, access control, physical security, industrial doors, loading bays and road-safety systems. We bring product selection, local fabrication, system integration and field support together under one accountable team.','Our approach begins with the site rather than a product catalogue. We study movement, risk, duty cycle, available infrastructure and the people who will operate the system before recommending a solution.']],
    ['type'=>'stats','items'=>[['value'=>'15+','label'=>'Years of market experience'],['value'=>'9','label'=>'Core product families'],['value'=>'Pakistan','label'=>'Nationwide project support'],['value'=>'End-to-end','label'=>'Survey through after-sales service']]],
    ['type'=>'cards','eyebrow'=>'What we deliver','title'=>'Capability across the project lifecycle','items'=>[['title'=>'Consultation and design','body'=>'Site review, application assessment, equipment selection and integration planning.'],['title'=>'Supply and fabrication','body'=>'International product sourcing alongside locally fabricated doors, gates and security equipment.'],['title'=>'Installation and commissioning','body'=>'Coordinated mechanical, electrical and control work followed by scenario-based testing.'],['title'=>'Service and support','body'=>'Operator guidance, preventive maintenance, troubleshooting, repairs and compatible spare parts.']]],
];
$pages['company-history']['blocks'] = [
        ['type'=>'story','eyebrow'=>'Company history','title'=>'Founded with innovation, growing through capability','body'=>['ViaTech developed from a specialist entrance-automation business into a broader technology and engineering company. Each new capability followed a practical customer need: better control, safer movement, stronger physical protection or more dependable industrial operation.']],
    ['type'=>'timeline','items'=>[['year'=>'Foundation','title'=>'Automatic entry systems','body'=>'The early portfolio focused on automatic doors, sliding and swing gates, shutters and the controls needed for safe operation.'],['year'=>'Expansion','title'=>'International collaboration','body'=>'Relationships with specialist manufacturers broadened the available range and strengthened product and application knowledge.'],['year'=>'Integration','title'=>'RFID and access systems','body'=>'Personnel and vehicle identification were added to connect physical entrances with permissions, records and automated decisions.'],['year'=>'Manufacturing','title'=>'Local fabrication','body'=>'Fabrication capability enabled made-to-measure gates, fire-rated doors, emergency exits and physical-security equipment.'],['year'=>'Industrial','title'=>'Loading bays and industrial doors','body'=>'The portfolio expanded into dock levellers, sectional doors, high-speed doors and controls for warehouses and production sites.'],['year'=>'Today','title'=>'Software-enabled systems and wider service','body'=>'Modern projects combine field equipment, management software, reporting, integration and ongoing technical support.']]],
];
$pages['core-values']['blocks'] = [
    ['type'=>'story','eyebrow'=>'How we conduct our work','title'=>'Commitment that extends beyond equipment','body'=>['Our standards guide how requirements are understood, how recommendations are made and how systems are handed over. They apply to everyday service calls as much as major projects.']],
    ['type'=>'cards','columns'=>4,'items'=>[['title'=>'Safety','body'=>'Protect users, technicians and the public through appropriate design, installation and working practices.'],['title'=>'Integrity','body'=>'Communicate honestly about scope, suitability, cost, limitations and project status.'],['title'=>'Vision','body'=>'Build a dependable technology company with lasting customer and partner relationships.'],['title'=>'Mission','body'=>'Make useful automation and security technology accessible with competent local support.'],['title'=>'Quality','body'=>'Select suitable materials and products, install carefully and verify operation before handover.'],['title'=>'Innovation','body'=>'Adopt better technologies when they provide a clear operational or safety benefit.'],['title'=>'Clients','body'=>'Understand the actual operating need and protect the customer’s long-term interest.'],['title'=>'Collaboration','body'=>'Coordinate commercial, technical, civil, electrical and operational stakeholders as one project team.']]],
];
$pages['our-team']['blocks'] = [
    ['type'=>'story','eyebrow'=>'People behind the systems','title'=>'Different disciplines, one accountable team','body'=>['A reliable installation needs more than one skill. Our work brings together consultation, sales engineering, project coordination, software and controls, fabrication, installation and after-sales service.']],
    ['type'=>'cards','items'=>[['title'=>'Professional excellence','body'=>'Team members are expected to understand their work, document it clearly and deliver to an agreed standard.'],['title'=>'Collaboration and integrity','body'=>'Information is shared across disciplines so customer commitments remain technically realistic.'],['title'=>'Innovation and adaptability','body'=>'We learn new platforms and adjust designs when site evidence shows a better approach.'],['title'=>'Commitment to growth','body'=>'Product learning, field experience and structured feedback strengthen the team over time.'],['title'=>'Customer-centred thinking','body'=>'Technical choices are judged by safety, usability, maintainability and value for the customer.']]],
    ['type'=>'steps','eyebrow'=>'Working together','title'=>'From first call to long-term support','items'=>[['title'=>'Commercial consultation','body'=>'Clarify objectives, budget and project context.'],['title'=>'Engineering review','body'=>'Develop the application and integration approach.'],['title'=>'Delivery team','body'=>'Coordinate fabrication, installation and commissioning.'],['title'=>'Service team','body'=>'Support operators and maintain the installed system.']]],
];
$pages['brand-partners']['blocks'] = [
    ['type'=>'story','eyebrow'=>'Technology partners','title'=>'Trusted partners, selected for the application','body'=>['We work with manufacturers whose products complement our automation, industrial-door and RFID capabilities. Partnership does not replace engineering judgement: every selection must still suit the site, usage and support plan.']],
    ['type'=>'entities','items'=>[['name'=>'Powertech Automation Inc.','meta'=>'Gate and entrance automation','body'=>'Automation equipment for sliding gates, swing gates and related entrance-control applications.'],['name'=>'YUOU Industrial Doors','meta'=>'Industrial entrance systems','body'=>'High-speed, sectional and specialist door technology for intensive commercial and industrial environments.'],['name'=>'Hongfa Doors','meta'=>'Door systems','body'=>'Industrial door products and components for controlled, durable building openings.'],['name'=>'Chafon Technology Co. Ltd.','meta'=>'UHF RFID','body'=>'Long-range RFID readers, desktop encoders, cards and vehicle tags for identification systems.'],['name'=>'Hanmoke Mechanical Equipment Co., Ltd.','meta'=>'Loading-bay equipment','body'=>'Dock and material-movement equipment for warehouse and dispatch operations.']]],
    ['type'=>'list','title'=>'How partner products are evaluated','items'=>['Application and duty-cycle suitability','Safety functions and relevant compliance','Compatibility with controls and management software','Documentation, spare parts and technical support','Long-term maintainability and upgrade path']],
];
$pages['our-brands']['blocks'] = [
        ['type'=>'story','eyebrow'=>'Registered trademarks','title'=>'Brands developed around specialist applications','body'=>['Our in-house brands organise focused product families and locally supported systems. Each has a distinct role within the wider ViaTech portfolio.']],
    ['type'=>'entities','items'=>[['name'=>'MOVE','meta'=>'Automation and movement','body'=>'Automatic doors, gate operators, road barriers, sensors, detectors and related movement-control equipment.'],['name'=>'DEFEND','meta'=>'Physical security','body'=>'Road blockers, tyre killers, manual barriers and under-vehicle inspection solutions for protected sites.'],['name'=>'eVACS','meta'=>'Electronic vehicle access control','body'=>'UHF RFID readers and supporting technology for hands-free vehicle identification and managed entry.']]],
];
$pages['certifications']['blocks'] = [
    ['type'=>'story','eyebrow'=>'Commitment to standards','title'=>'Quality assurance and responsible compliance','body'=>['Standards help turn good intentions into repeatable work. We use documented requirements, suitable products, controlled installation practices and functional verification to improve consistency.']],
    ['type'=>'cards','items'=>[['title'=>'Commitment to standards','body'=>'Relevant product, electrical, fire-safety, access and manufacturer requirements are considered during selection and delivery.'],['title'=>'Quality assurance and compliance','body'=>'Project information, equipment data, installation checks and test results are recorded to support accountable handover.'],['title'=>'Continuous improvement','body'=>'Field feedback, service history and updated technical guidance are used to refine designs and working practices.']]],
    ['type'=>'list','title'=>'Typical handover evidence','items'=>['Approved equipment and scope records','Configuration and access-control information','Functional and safety test results','Operator guidance and maintenance advice','Warranty and support documentation']],
];
$pages['careers']['blocks'] = [
    ['type'=>'story','eyebrow'=>'Careers','title'=>'Join a team working on real technology infrastructure','body'=>['Our projects combine mechanics, electronics, software, fabrication and customer service. We value people who are practical, responsible, willing to learn and comfortable working across disciplines.']],
    ['type'=>'cards','eyebrow'=>'Why work with us','items'=>[['title'=>'Varied technical work','body'=>'Learn across automatic entrances, industrial systems, RFID, access control and physical security.'],['title'=>'Field and office experience','body'=>'Understand the complete journey from requirement and proposal to installation and support.'],['title'=>'Room to grow','body'=>'Develop through product learning, mentoring, site experience and increasing project responsibility.']]],
    ['type'=>'list','title'=>'Roles we commonly consider','items'=>['Sales and application engineers','Electrical and controls technicians','Mechanical installers and fabricators','Software and integration specialists','Project coordinators','Customer service and support professionals']],
    ['type'=>'cta','title'=>'Send us your CV','body'=>'Introduce yourself, describe the kind of work you want to do and attach your current CV through the contact form.','label'=>'Contact the careers team','href'=>'/contact'],
];
$pages['latest-news']['blocks'] = [
        ['type'=>'story','eyebrow'=>'Company updates','title'=>'Developments across products, partnerships and production','body'=>['News from ViaTech focuses on changes that affect customers: additions to the portfolio, stronger technical partnerships and improvements in local capability.']],
    ['type'=>'news','items'=>[['title'=>'New product lines introduced','date'=>'Portfolio update','body'=>'The expanded range now covers more automatic-door operators, gate motors, UHF RFID readers, industrial PCs, road barriers, safety sensors and supporting accessories.'],['title'=>'Partnerships with industry specialists','date'=>'Partner network','body'=>'Technical relationships with automation, industrial-door, RFID and loading-bay manufacturers broaden the options available for project-specific designs.'],['title'=>'Manufacturing capability continues to grow','date'=>'Local production','body'=>'Fabrication supports custom gates, industrial openings, fire-rated doors, emergency exits and physical-security equipment sized around site requirements.']]],
];
$pages['solutions']['blocks'] = [
    ['type'=>'story','eyebrow'=>'Integrated solutions','title'=>'Start with the operating problem, not a product','body'=>['A complete solution defines how identification, physical equipment, safety devices, software and operators work together. The system must also account for power loss, communication failure, emergency access and future expansion.']],
    ['type'=>'links','items'=>[['title'=>'Parking management solution','body'=>'Control entry and exit, identify users, understand occupancy and support payment or validation workflows.','href'=>'/parking-management-guidance-solution'],['title'=>'Road safety','body'=>'Use detection, warning, channelisation and traffic-control equipment to reduce risk on internal roads.','href'=>'/road-safety-solutions'],['title'=>'Personnel identification and visitor management','body'=>'Register visitors, verify identity, notify hosts and issue time-limited permissions.','href'=>'/visitor-management-solution'],['title'=>'Personnel access control','body'=>'Manage credentials, doors, turnstiles, schedules and event histories from one access policy.','href'=>'/personnel-access-control-solution'],['title'=>'Perimeter security solutions','body'=>'Combine gates, blockers, tyre killers, surveillance and controlled response at the site boundary.','href'=>'/perimeter-security-solutions'],['title'=>'E-TAG vehicle access control','body'=>'Use long-range RFID, vehicle detection and barriers for faster authorised entry.','href'=>'/rfid-etag-vehicle-access-control-solution'],['title'=>'Loading bay solution','body'=>'Coordinate dock levellers, industrial doors, traffic signals and safety interlocks.','href'=>'/loading-bay-solution']]],
];

$solutionBlocks = [
    'rfid-etag-vehicle-access-control-solution'=>[
        ['type'=>'story','eyebrow'=>'Vehicle identification and automation','title'=>'Hands-free access for authorised vehicles','body'=>['E-TAG vehicle access uses passive UHF RFID credentials to identify a registered vehicle before it reaches the control point. A reader sends the credential to the access application, which checks the vehicle, entrance and time permissions before issuing an open command.','The solution is suited to staff parking, residential communities, factories, campuses, logistics sites and controlled facilities where faster movement and a reliable event history are required.']],
        ['type'=>'cards','eyebrow'=>'What is included','items'=>[['title'=>'RFID windshield tags and cards','body'=>'Unique credentials assigned to vehicles, users or temporary access records.'],['title'=>'Long-range RFID readers','body'=>'Weather-suitable readers positioned and tuned for the lane geometry and required reading distance.'],['title'=>'Access-control software','body'=>'Vehicle registration, permission rules, entry events, exception handling and operator reporting.'],['title'=>'Automatic road barriers','body'=>'Boom barriers or compatible gates sized for the opening speed and traffic duty.'],['title'=>'Vehicle loop detectors','body'=>'Presence and safety detection used to coordinate opening, passage and safe closing.'],['title'=>'Traffic signals and safety devices','body'=>'Red/green indication, photocells, emergency controls and audible or visual warnings where needed.']]],
        ['type'=>'steps','eyebrow'=>'Operating sequence','title'=>'From approach to recorded entry','items'=>[['title'=>'Vehicle approaches','body'=>'The safety or presence detector confirms a vehicle in the controlled lane.'],['title'=>'Credential is read','body'=>'The RFID reader captures the assigned tag without requiring the driver to stop and present it manually.'],['title'=>'Permission is checked','body'=>'The system applies vehicle, entrance, schedule and status rules.'],['title'=>'Access is completed','body'=>'The barrier operates, passage is monitored and the event is stored for reporting.']]],
        ['type'=>'products','title'=>'Related products','slugs'=>['alien-h3-iso18000-6c-epc-gen2-uhf-windshield-tag','alien-h3-iso18000-6cepc-gen2-uhf-rfid-card','move-vxd1-single-channel-vehicle-loop-detector','rgl200-ax-arrow-cfross-led-traffic-signal-light','move-ds6a-automatic-road-barrier','evacs-u79-series-uhf-rfid-high-performance-integrated-reader']],
    ],
    'loading-bay-solution'=>[
        ['type'=>'story','eyebrow'=>'Industrial movement and dock safety','title'=>'Coordinate vehicles, doors and dock equipment','body'=>['A loading bay must bridge the height and distance between a building and different delivery vehicles without creating uncontrolled movement. The solution brings dock equipment, industrial doors, traffic indication and operating logic into one sequence.','The scope is developed around vehicle types, bay dimensions, loading frequency, environmental separation, forklift movement, safety policy and the building structure.']],
        ['type'=>'cards','eyebrow'=>'What is included','items'=>[['title'=>'Hydraulic dock leveller','body'=>'Creates a controlled bridge between the dock floor and vehicle bed for material-handling equipment.'],['title'=>'Industrial sectional door','body'=>'Provides a durable, insulated opening that rises clear of the working area.'],['title'=>'High-speed PVC door','body'=>'Separates internal zones while supporting frequent forklift and personnel movement.'],['title'=>'Automatic roller shutter','body'=>'Secures openings and provides a compact closure where the application permits.'],['title'=>'Traffic indication','body'=>'External and internal signals communicate when a driver or dock operator may proceed.'],['title'=>'Controls and interlocks','body'=>'Prevent unsafe operating sequences and provide emergency or maintenance modes.']]],
        ['type'=>'steps','eyebrow'=>'Safe sequence','title'=>'A controlled loading operation','items'=>[['title'=>'Vehicle arrives','body'=>'The driver is directed to the correct bay and receives a clear stop indication.'],['title'=>'Vehicle is secured','body'=>'Site procedures confirm safe positioning before dock or door equipment is enabled.'],['title'=>'Bay is opened','body'=>'The door and dock leveller operate in the agreed interlocked order.'],['title'=>'Loading is completed','body'=>'Equipment returns to a safe position before the vehicle is released.']]],
        ['type'=>'products','title'=>'Related products','slugs'=>['hydraulic-dock-leveler-manufacturer-in-pakistan','high-speed-pvc-roll-up-doors','industrial-sectional-door','automatic-roller-shutter']],
    ],
    'parking-management-guidance-solution'=>[
        ['type'=>'story','eyebrow'=>'Parking operations','title'=>'Manage access, occupancy and the driver journey','body'=>['Parking management can range from a simple authorised-user barrier to a multi-lane facility with tickets, RFID, ANPR, validation, payment and live occupancy guidance. The appropriate level depends on who uses the parking and how the operator needs to manage it.','A workable design considers peak arrival and departure volumes, visitor handling, lost credentials, tailgating, power failure, manual release, revenue controls and reporting.']],
        ['type'=>'cards','items'=>[['title'=>'Entry and exit stations','body'=>'Issue or validate tickets, credentials or vehicle records at controlled lanes.'],['title'=>'Barrier and gate control','body'=>'Operate physical entrances with vehicle detection and safe-closing logic.'],['title'=>'RFID and ANPR identification','body'=>'Recognise registered vehicles automatically or support staff and permit-holder access.'],['title'=>'Occupancy and guidance','body'=>'Count vehicles by facility or zone and direct drivers with signs or space indicators.'],['title'=>'Payment and validation','body'=>'Support operator-led, kiosk or compatible digital payment and tenant validation workflows.'],['title'=>'Management reporting','body'=>'Review occupancy, access events, exceptions, transactions and equipment status.']]],
        ['type'=>'list','title'=>'Typical environments','items'=>['Shopping centres and public parking','Corporate offices and mixed-use buildings','Hospitals, universities and campuses','Hotels, clubs and event venues','Housing societies and resident parking','Factories and staff parking facilities']],
    ],
    'perimeter-security-solutions'=>[
        ['type'=>'story','eyebrow'=>'Layered site protection','title'=>'Deter, detect, delay and respond at the boundary','body'=>['Perimeter security is developed from the threat, site layout and operating policy. Physical equipment alone is not enough: the design must explain how authorised movement continues, how suspicious activity is detected and what operators do when an event occurs.']],
        ['type'=>'cards','items'=>[['title'=>'Automated and manual gates','body'=>'Control routine vehicle movement and create a clear managed entrance.'],['title'=>'Road blockers and bollards','body'=>'Provide a stronger physical vehicle barrier for higher-risk access points.'],['title'=>'Tyre killers and directional spikes','body'=>'Restrict wrong-way or unauthorised vehicle movement where site policy permits.'],['title'=>'Under-vehicle inspection','body'=>'Support inspection of vehicle undercarriages at sensitive entrances.'],['title'=>'Pedestrian screening','body'=>'Use turnstiles, access readers and metal detection to manage people entering controlled zones.'],['title'=>'Detection and surveillance integration','body'=>'Connect alarms, cameras, intercoms and access events to the operator response.']]],
        ['type'=>'steps','eyebrow'=>'Design approach','title'=>'Security matched to the real risk','items'=>[['title'=>'Assess','body'=>'Identify assets, threats, vulnerable approaches and operational constraints.'],['title'=>'Layer','body'=>'Combine deterrence, detection, physical delay and controlled access.'],['title'=>'Integrate','body'=>'Define operator controls, alarms, surveillance views and fallback operation.'],['title'=>'Test','body'=>'Prove normal, denied, emergency and equipment-failure scenarios.']]],
    ],
    'personnel-access-control-solution'=>[
        ['type'=>'story','eyebrow'=>'People and permissions','title'=>'Control who can enter, where and when','body'=>['Personnel access control replaces unmanaged keys and informal permission with identifiable users, controlled doors or turnstiles, schedules and searchable events. The system can begin with one entrance and expand across departments or sites.']],
        ['type'=>'cards','items'=>[['title'=>'Credentials','body'=>'Cards, PINs, fingerprints, faces or mobile credentials selected according to users and risk.'],['title'=>'Readers and terminals','body'=>'Devices capture the credential and provide clear access-granted or denied feedback.'],['title'=>'Controllers and software','body'=>'Store permissions, schedules, door logic and access events.'],['title'=>'Locks and door hardware','body'=>'Electromagnetic locks, dead bolts, exit buttons, emergency releases and monitored contacts.'],['title'=>'Turnstiles and speed gates','body'=>'Regulate pedestrian flow where a normal controlled door is not enough.'],['title'=>'Attendance integration','body'=>'Use compatible terminal events to support time and attendance workflows.']]],
        ['type'=>'list','title'=>'Policies the system can support','items'=>['Access by department, role or individual','Time schedules, holidays and temporary access','Anti-passback and occupancy-aware controls','Visitor, contractor and expiring credentials','Door-held, forced-entry and denied-access alarms','Event export and investigation reporting']],
    ],
    'visitor-management-solution'=>[
        ['type'=>'story','eyebrow'=>'Identity and reception workflow','title'=>'Welcome expected visitors and control exceptions','body'=>['Visitor management organises the journey from invitation to departure. It gives reception and security teams the information needed to verify a guest, contact the host, issue appropriate access and know who remains on site.']],
        ['type'=>'steps','eyebrow'=>'Visitor journey','title'=>'A clear process from invitation to checkout','items'=>[['title'=>'Pre-register','body'=>'The host or reception team records visit details and any approval requirement.'],['title'=>'Verify and check in','body'=>'Reception confirms identity, purpose, host and required site acknowledgements.'],['title'=>'Issue permission','body'=>'A badge or temporary credential is assigned with the correct areas and expiry time.'],['title'=>'Monitor and check out','body'=>'The current visitor list remains visible until the visit is closed and credentials are returned.']]],
        ['type'=>'cards','items'=>[['title'=>'Host notification','body'=>'Notify the responsible employee when a guest arrives.'],['title'=>'Badge and pass management','body'=>'Issue identifiable visitor records and time-limited credentials.'],['title'=>'Watch lists and approval','body'=>'Route sensitive or unexpected visits through the correct security decision.'],['title'=>'Emergency visibility','body'=>'Provide a current list of checked-in visitors for accountability.']]],
    ],
    'road-safety-solutions'=>[
        ['type'=>'story','eyebrow'=>'Safer internal traffic','title'=>'Make hazards visible and movement predictable','body'=>['Road-safety solutions for campuses, factories, parking areas and communities should respond to observed hazards. Blind junctions, pedestrian crossings, speeding, wrong-way movement and loading traffic each require a different combination of controls.']],
        ['type'=>'cards','items'=>[['title'=>'Traffic signals and warning lights','body'=>'Communicate right-of-way, hazards and controlled movement clearly.'],['title'=>'Vehicle detection','body'=>'Trigger signals, barriers or warnings when a vehicle enters a defined area.'],['title'=>'Speed management','body'=>'Use signs, markings and appropriate physical controls to reinforce site limits.'],['title'=>'Pedestrian protection','body'=>'Improve visibility and separation at crossings and shared movement areas.'],['title'=>'Channelisation','body'=>'Guide traffic with barriers, bollards, cones and lane definition.'],['title'=>'Wrong-way control','body'=>'Detect, warn or physically discourage travel against the permitted direction.']]],
        ['type'=>'steps','eyebrow'=>'Safety review','title'=>'From hazard to practical control','items'=>[['title'=>'Observe','body'=>'Review actual vehicle and pedestrian movement at relevant times.'],['title'=>'Identify','body'=>'Record conflict points, visibility limits and unsafe behaviour.'],['title'=>'Control','body'=>'Choose engineering, visual and procedural measures suited to the risk.'],['title'=>'Review','body'=>'Confirm that users understand the change and monitor its effectiveness.']]],
    ],
];
foreach($solutionBlocks as $slug=>$blocks)$pages[$slug]['blocks']=$blocks;

$pages['our-projects']['blocks'] = [
    ['type'=>'story','eyebrow'=>'Project portfolio','title'=>'Installed systems across demanding environments','body'=>['Our portfolio spans armed-forces facilities, offices, factories, educational campuses, residential developments and private properties. The work ranges from a single automated entrance to integrated access, industrial-door and physical-security packages.','Project cards identify the site and broad scope. Detailed references, equipment schedules or site-specific information can be discussed where customer confidentiality permits.']],
    ['type'=>'stats','items'=>[['value'=>'23','label'=>'Portfolio subjects'],['value'=>'6','label'=>'Project sectors'],['value'=>'Multiple','label'=>'Automation and security disciplines'],['value'=>'Lifecycle','label'=>'Installation through support']]],
];

$pages['support']['blocks'] = [
    ['type'=>'story','eyebrow'=>'Customer support','title'=>'How can we help you today?','body'=>['Choose the support route that matches your need. Providing the product model, site, project reference and a clear description helps the team respond efficiently.']],
    ['type'=>'links','items'=>[['title'=>'Product demonstration','body'=>'Arrange a focused walkthrough of a product, system or operating workflow before selection.','href'=>'/product-demonstration'],['title'=>'Technical support','body'=>'Get help with faults, operation, configuration, maintenance, spare parts or an existing installation.','href'=>'/technical-support'],['title'=>'Warranty','body'=>'Understand coverage, exclusions, required information and the claim process for supplied products.','href'=>'/warranty']]],
    ['type'=>'cta','title'=>'Need immediate assistance?','body'=>'Call the published support number or send a message with the site and system details. Isolate safety-related faults and do not operate damaged equipment.','label'=>'Contact support','href'=>'/contact'],
];
$pages['technical-support']['blocks'] = [
    ['type'=>'story','eyebrow'=>'Technical assistance','title'=>'Tech support made simple','body'=>['Start with the site, product or system name, the behaviour you expected, what actually happened and any message or indicator shown. Mention recent power, network, configuration or construction changes.']],
    ['type'=>'cards','eyebrow'=>'Contact channels','items'=>[['title'=>'Call support','body'=>'Best for urgent operational faults where a technician needs to ask diagnostic questions.'],['title'=>'WhatsApp support','body'=>'Useful for sharing equipment labels, indicator photos, short videos and site-location details.'],['title'=>'Email support','body'=>'Suitable for non-urgent requests, documents, service histories and detailed multi-item issues.']]],
    ['type'=>'list','title'=>'Common support topics','items'=>['Automatic door or gate does not open or close correctly','Barrier remains open, closed or moves unexpectedly','RFID tag, access card or biometric user is not recognised','Sensor, loop detector or safety beam alignment problems','Door lock, exit button or emergency release issue','Software login, permission, report or communication problem','Preventive maintenance, spare-part and upgrade requests']],
    ['type'=>'steps','eyebrow'=>'What happens next','title'=>'A controlled support response','items'=>[['title'=>'Triage','body'=>'Confirm safety, impact and essential system details.'],['title'=>'Diagnose','body'=>'Guide appropriate checks or review available evidence.'],['title'=>'Resolve or escalate','body'=>'Apply a remote correction, identify a part or arrange a site visit.'],['title'=>'Record','body'=>'Document the action and any maintenance recommendation.']]],
];
$pages['warranty']['blocks'] = [
    ['type'=>'story','eyebrow'=>'Product warranty information','title'=>'Clear coverage and a documented claim process','body'=>['Warranty terms depend on the supplied product, manufacturer and project agreement. The invoice, quotation or handover documentation remains the authority for the applicable period and conditions.']],
    ['type'=>'cards','items'=>[['title'=>'Warranty coverage','body'=>'Manufacturing defects or product failures confirmed to fall within the supplied warranty terms.'],['title'=>'Duration of warranty','body'=>'The period begins from the documented supply, installation or handover date stated in project records.'],['title'=>'What is covered','body'=>'Assessment and the repair, replacement or manufacturer process applicable to an accepted claim.'],['title'=>'What is not covered','body'=>'Misuse, unauthorised modification, accident, vandalism, unsuitable power, water ingress outside rating, consumable wear or ignored maintenance.']]],
    ['type'=>'steps','eyebrow'=>'Claim procedure','title'=>'How to request warranty support','items'=>[['title'=>'Gather records','body'=>'Locate the invoice or project reference, model, serial number and relevant warranty document.'],['title'=>'Describe the fault','body'=>'Explain the symptom, when it began and the operating conditions.'],['title'=>'Share evidence','body'=>'Provide clear photos, video or error information when requested.'],['title'=>'Allow assessment','body'=>'Follow return, inspection or site-visit instructions before repair or replacement is authorised.']]],
    ['type'=>'notice','title'=>'Do not dismantle equipment before assessment','body'=>'Unauthorised repair or alteration can affect coverage and may create a safety risk. Contact support first.'],
];
$pages['product-demonstration']['blocks'] = [
    ['type'=>'story','eyebrow'=>'Evaluate before selection','title'=>'See the equipment and operating workflow in action','body'=>['A useful demonstration is based on the decision you need to make. Tell us the product family, application, expected users and site constraints so the session can focus on relevant operation, safety and integration.']],
    ['type'=>'steps','eyebrow'=>'Demonstration process','title'=>'A focused session, not a generic presentation','items'=>[['title'=>'Define the objective','body'=>'Identify the technology and questions your team needs answered.'],['title'=>'Choose the format','body'=>'Arrange a showroom, remote, site or project-specific demonstration where practical.'],['title'=>'Walk through operation','body'=>'Review normal use, controls, safety functions, manual modes and management features.'],['title'=>'Plan the next step','body'=>'Record open questions and prepare a site survey, scope or quotation if required.']]],
    ['type'=>'list','title'=>'Demonstrations can cover','items'=>['Automatic sliding, swing and gate operation','Road barriers, vehicle detectors and safety controls','RFID tags, readers and vehicle-access software','Personnel access terminals, locks and turnstiles','Industrial doors and loading-bay equipment','Physical-security equipment and operator controls']],
    ['type'=>'cta','title'=>'Request a product demonstration','body'=>'Tell us what you want to evaluate and who will attend. The team will confirm a suitable format and available date.','label'=>'Arrange a demonstration','href'=>'/contact'],
];

return $pages;
