import ProductCard from '@/components/product-card';
import PublicLayout from '@/layouts/public-layout';
import { Head, Link } from '@inertiajs/react';
import { ArrowRight, CheckCircle2, Cpu, ShieldCheck, Wrench } from 'lucide-react';
import { useState } from 'react';

export default function Content({settings,page,relatedProducts={}}:any){const Icon=page.group==='Support'?Wrench:page.group==='Solutions'?Cpu:ShieldCheck;return <PublicLayout settings={settings}><Head title={page.title}><meta name="description" content={page.intro}/></Head><section className="page-hero overflow-hidden"><div className="mx-auto grid max-w-6xl items-center gap-12 px-5 lg:grid-cols-[1fr_340px]"><div><p className="section-kicker">{page.group}</p><h1 className="max-w-4xl text-5xl font-black tracking-tight md:text-7xl">{page.title}</h1><p className="mt-7 max-w-3xl text-xl leading-8 text-slate-300">{page.intro}</p></div><div aria-hidden="true" className="relative mx-auto grid aspect-square w-full max-w-xs place-items-center rounded-[3rem] border border-cyan-300/20 bg-[radial-gradient(circle_at_50%_45%,rgba(34,211,238,.22),transparent_58%)]"><div className="absolute inset-8 rounded-full border border-dashed border-cyan-300/20"/><Icon className="h-24 w-24 text-cyan-300" strokeWidth={1}/></div></div></section><main className="mx-auto max-w-6xl space-y-24 px-5 py-20"><Blocks blocks={page.blocks||[]} products={relatedProducts}/>{page.portfolio&&<Portfolio portfolio={page.portfolio}/>}<CTA title="Talk through your requirement" body="Share the site, operating need and any existing equipment. Our team will help define a sensible next step." label="Contact us" href="/contact"/></main></PublicLayout>}

function Blocks({blocks,products}:any){return <>{blocks.map((block:any,index:number)=><Block key={`${block.type}-${index}`} block={block} products={products}/>)}</>}
function Block({block,products}:any){
    if(block.type==='story')return <section className="grid gap-8 lg:grid-cols-[.38fr_1fr]"><div><p className="section-kicker">{block.eyebrow}</p></div><div><h2 className="text-3xl font-black md:text-5xl">{block.title}</h2><div className="mt-6 space-y-5">{block.body.map((text:string)=><p key={text} className="max-w-3xl text-lg leading-8 text-slate-300">{text}</p>)}</div></div></section>;
    if(block.type==='stats')return <section className="grid gap-px overflow-hidden rounded-3xl border border-white/10 bg-white/10 sm:grid-cols-2 lg:grid-cols-4">{block.items.map((item:any)=><div key={item.label} className="bg-[#080d17] p-7"><strong className="text-3xl font-black text-cyan-300">{item.value}</strong><p className="mt-2 text-sm text-slate-400">{item.label}</p></div>)}</section>;
    if(block.type==='cards')return <section><Header block={block}/><div className={`mt-8 grid gap-5 sm:grid-cols-2 ${block.columns===4?'xl:grid-cols-4':'lg:grid-cols-3'}`}>{block.items.map((item:any)=><article key={item.title} className="rounded-2xl border border-white/10 bg-white/[.03] p-7"><CheckCircle2 className="h-6 w-6 text-cyan-300"/><h3 className="mt-6 text-xl font-bold">{item.title}</h3><p className="mt-3 leading-7 text-slate-400">{item.body}</p></article>)}</div></section>;
    if(block.type==='timeline')return <section><h2 className="text-3xl font-black md:text-4xl">Our development</h2><div className="relative mt-10 space-y-0 before:absolute before:bottom-0 before:left-[1.45rem] before:top-0 before:w-px before:bg-cyan-300/20">{block.items.map((item:any)=><article key={item.title} className="relative grid gap-3 py-6 pl-20 md:grid-cols-[180px_1fr]"><span className="absolute left-0 grid h-12 w-12 place-items-center rounded-full border border-cyan-300/30 bg-[#080d17] text-xs font-black text-cyan-300">{item.year.slice(0,4)}</span><p className="font-bold text-cyan-300">{item.year}</p><div><h3 className="text-xl font-bold">{item.title}</h3><p className="mt-2 leading-7 text-slate-400">{item.body}</p></div></article>)}</div></section>;
    if(block.type==='entities')return <section><h2 className="text-3xl font-black md:text-4xl">Portfolio</h2><div className="mt-8 grid gap-5 md:grid-cols-2 lg:grid-cols-3">{block.items.map((item:any)=><article key={item.name} className="rounded-3xl border border-white/10 bg-[linear-gradient(145deg,rgba(34,211,238,.08),rgba(255,255,255,.02))] p-8"><div className="text-xs font-bold uppercase tracking-[.2em] text-cyan-300">{item.meta}</div><h3 className="mt-5 text-2xl font-black">{item.name}</h3><p className="mt-4 leading-7 text-slate-400">{item.body}</p></article>)}</div></section>;
    if(block.type==='list')return <section className="rounded-3xl border border-white/10 bg-white/[.03] p-8 md:p-10"><h2 className="text-3xl font-black">{block.title}</h2><div className="mt-7 grid gap-3 md:grid-cols-2">{block.items.map((item:string)=><div key={item} className="flex gap-3 rounded-xl bg-black/15 p-4"><CheckCircle2 className="mt-0.5 h-5 w-5 shrink-0 text-cyan-300"/><span className="leading-6 text-slate-300">{item}</span></div>)}</div></section>;
    if(block.type==='steps')return <section><Header block={block}/><div className="mt-9 grid gap-4 md:grid-cols-2 lg:grid-cols-4">{block.items.map((item:any,index:number)=><article key={item.title} className="relative rounded-2xl border border-white/10 p-6"><span className="text-xs font-black text-cyan-300">{String(index+1).padStart(2,'0')}</span><h3 className="mt-5 text-lg font-bold">{item.title}</h3><p className="mt-3 text-sm leading-6 text-slate-400">{item.body}</p></article>)}</div></section>;
    if(block.type==='links')return <section className="grid gap-5 md:grid-cols-2">{block.items.map((item:any)=><Link key={item.href} href={item.href} className="group rounded-3xl border border-white/10 bg-white/[.03] p-8 hover:border-cyan-300/30"><h3 className="text-2xl font-bold">{item.title}</h3><p className="mt-4 leading-7 text-slate-400">{item.body}</p><span className="mt-6 inline-flex items-center gap-2 text-sm font-bold text-cyan-300">Explore <ArrowRight className="h-4 w-4 transition group-hover:translate-x-1"/></span></Link>)}</section>;
    if(block.type==='news')return <section className="space-y-5">{block.items.map((item:any)=><article key={item.title} className="grid gap-5 rounded-2xl border border-white/10 p-7 md:grid-cols-[180px_1fr]"><p className="text-xs font-bold uppercase tracking-wider text-cyan-300">{item.date}</p><div><h2 className="text-2xl font-bold">{item.title}</h2><p className="mt-3 leading-7 text-slate-400">{item.body}</p></div></article>)}</section>;
    if(block.type==='products'){const items=block.slugs.map((slug:string)=>products[slug]).filter(Boolean);return <section><h2 className="text-3xl font-black">{block.title}</h2><div className="mt-8 grid gap-5 md:grid-cols-2 lg:grid-cols-3">{items.map((product:any)=><ProductCard key={product.id} product={product}/>)}</div></section>}
    if(block.type==='notice')return <section className="rounded-3xl border border-amber-300/20 bg-amber-300/[.06] p-8"><h2 className="text-2xl font-bold text-amber-200">{block.title}</h2><p className="mt-3 leading-7 text-slate-300">{block.body}</p></section>;
    if(block.type==='cta')return <CTA {...block}/>;
    return null;
}
function Header({block}:any){return <div><p className="section-kicker">{block.eyebrow||'In detail'}</p>{block.title&&<h2 className="mt-3 text-3xl font-black md:text-4xl">{block.title}</h2>}</div>}
function CTA({title,body,label,href}:any){return <section className="flex flex-col justify-between gap-6 rounded-3xl border border-cyan-300/20 bg-cyan-300/[.05] p-9 sm:flex-row sm:items-center"><div><h2 className="text-2xl font-bold">{title}</h2><p className="mt-2 max-w-2xl text-slate-400">{body}</p></div><Link href={href} className="inline-flex shrink-0 items-center justify-center gap-2 rounded-full bg-cyan-300 px-6 py-3 font-bold text-slate-950">{label}<ArrowRight className="h-4 w-4"/></Link></section>}
function Portfolio({portfolio}:any){const [sector,setSector]=useState('All');const items=sector==='All'?portfolio.items:portfolio.items.filter((item:any)=>item.sector===sector);return <section><p className="section-kicker">Selected portfolio</p><h2 className="mt-3 text-3xl font-black md:text-4xl">Projects by sector</h2><div className="mt-6 flex flex-wrap gap-2">{portfolio.sectors.map((item:string)=><button type="button" key={item} onClick={()=>setSector(item)} className={`rounded-full px-4 py-2 text-sm ${sector===item?'bg-cyan-300 font-bold text-slate-950':'border border-white/10 text-slate-300'}`}>{item}</button>)}</div><div className="mt-8 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{items.map((item:any)=><article key={item.name} className="rounded-2xl border border-white/10 bg-white/[.03] p-6"><p className="text-xs font-bold uppercase tracking-wider text-cyan-300">{item.sector}</p><h3 className="mt-3 text-xl font-bold">{item.name}</h3><p className="mt-3 text-sm leading-6 text-slate-400">{item.scope}</p></article>)}</div></section>}
