import PublicLayout from '@/layouts/public-layout';
import { Head, useForm } from '@inertiajs/react';
import { FormEvent } from 'react';

export default function Contact({ settings, products }: any) {
    const form=useForm<any>({type:'quote',name:'',company:'',email:'',phone:'',city:'',subject:'',message:'',products:[{id:'',quantity:1}],attachments:[]});
    const submit=(e:FormEvent) => {e.preventDefault();form.post('/contact',{forceFormData:true,preserveScroll:true});};
    return <PublicLayout settings={settings}><Head title="Contact & quotation request" /><section className="page-hero"><div className="mx-auto max-w-7xl px-5"><p className="section-kicker">Talk to Technoout</p><h1 className="section-title">Let’s engineer the right solution.</h1></div></section><section className="mx-auto grid max-w-7xl gap-12 px-5 py-16 lg:grid-cols-[.7fr_1.3fr]"><div><h2 className="text-2xl font-bold">Our offices</h2>{settings.locations.map((office:any) => <div key={office.id} className="mt-6 rounded-2xl border border-white/10 bg-white/[.03] p-6"><h3 className="font-bold text-cyan-300">{office.name}</h3><p className="mt-3 text-sm leading-6 text-slate-400">{office.address_line_1}<br />{office.city}, {office.country}</p>{office.contacts.map((contact:any) => <p key={contact.id} className="mt-2 text-sm">{contact.label}: <span className="text-slate-400">{contact.value}</span></p>)}</div>)}</div>
            <form onSubmit={submit} className="rounded-3xl border border-white/10 bg-white/[.035] p-6 md:p-10"><div className="grid gap-5 md:grid-cols-2"><select className="form-input" value={form.data.type} onChange={e=>form.setData('type',e.target.value)}><option value="quote">Quotation request</option><option value="general">General inquiry</option></select><input className="form-input" placeholder="Full name *" value={form.data.name} onChange={e=>form.setData('name',e.target.value)} required /><input className="form-input" placeholder="Company" value={form.data.company} onChange={e=>form.setData('company',e.target.value)} /><input className="form-input" type="email" placeholder="Email *" value={form.data.email} onChange={e=>form.setData('email',e.target.value)} required /><input className="form-input" placeholder="Phone" value={form.data.phone} onChange={e=>form.setData('phone',e.target.value)} /><input className="form-input" placeholder="City" value={form.data.city} onChange={e=>form.setData('city',e.target.value)} /><select className="form-input md:col-span-2" value={form.data.products[0].id} onChange={e=>form.setData('products',[{id:e.target.value,quantity:1}])}><option value="">Select a product (optional)</option>{products.map((item:any) => <option key={item.id} value={item.id}>{item.name}</option>)}</select><input className="form-input md:col-span-2" placeholder="Subject" value={form.data.subject} onChange={e=>form.setData('subject',e.target.value)} /><textarea className="form-input min-h-36 md:col-span-2" placeholder="Describe your site, requirements and timeline *" value={form.data.message} onChange={e=>form.setData('message',e.target.value)} required /><input type="file" multiple accept=".pdf,.jpg,.jpeg,.png" onChange={e=>form.setData('attachments',Array.from(e.target.files||[]))} className="form-input md:col-span-2" /></div>{Object.keys(form.errors).length>0&&<p className="mt-4 text-sm text-red-300">{Object.values(form.errors)[0] as string}</p>}<button disabled={form.processing} className="mt-7 rounded-full bg-cyan-300 px-8 py-4 font-bold text-slate-950">{form.processing?'Sending…':'Submit request'}</button></form>
        </section></PublicLayout>;
}
