<?php
namespace App\Http\Controllers;
use App\Models\{Category,ContentPage,Inquiry,Product,Quotation,Invoice};
use App\Services\BusinessSettings;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Inertia\Inertia;
class PublicSiteController extends Controller {
    public function home(){ return Inertia::render('public/home',['settings'=>BusinessSettings::public(),'categories'=>Category::withCount('products')->whereNull('parent_id')->where('is_active',true)->orderBy('sort_order')->get(),'products'=>Product::with('category')->where('is_published',true)->where('is_featured',true)->take(6)->get(),'solutions'=>ContentPage::where('type','solution')->where('is_published',true)->orderBy('sort_order')->take(6)->get()]); }
    public function catalog(Request $request){ $products=Product::with('category')->where('is_published',true)->when($request->search,fn($q,$v)=>$q->where(fn($x)=>$x->where('name','like','%'.$v.'%')->orWhere('summary','like','%'.$v.'%')))->when($request->category,fn($q,$v)=>$q->whereHas('category',fn($x)=>$x->where('slug',$v)))->latest()->paginate(12)->withQueryString(); return Inertia::render('public/catalog',['settings'=>BusinessSettings::public(),'products'=>$products,'categories'=>Category::where('is_active',true)->orderBy('name')->get(),'filters'=>$request->only('search','category')]); }
    public function product(Product $product){ abort_unless($product->is_published,404); return Inertia::render('public/product',['settings'=>BusinessSettings::public(),'product'=>$product->load('category'),'related'=>Product::where('category_id',$product->category_id)->whereKeyNot($product)->where('is_published',true)->take(3)->get()]); }
    public function page(string $slug){ $page=ContentPage::where('slug',$slug)->where('is_published',true)->firstOrFail(); return Inertia::render('public/content',['settings'=>BusinessSettings::public(),'page'=>$page]); }
    public function contact(){ return Inertia::render('public/contact',['settings'=>BusinessSettings::public(),'products'=>Product::where('is_published',true)->orderBy('name')->get(['id','name'])]); }
    public function submitContact(Request $request){ $data=$request->validate(['type'=>'required|in:general,quote','name'=>'required|string|max:150','company'=>'nullable|string|max:150','email'=>'required|email|max:190','phone'=>'nullable|string|max:50','city'=>'nullable|string|max:100','subject'=>'nullable|string|max:190','message'=>'required|string|max:5000','products'=>'nullable|array|max:20','products.*.id'=>'nullable|exists:products,id','products.*.quantity'=>'nullable|numeric|min:0.01|max:100000','attachments'=>'nullable|array|max:5','attachments.*'=>'file|mimes:pdf,jpg,jpeg,png|max:10240']); $paths=collect($request->file('attachments',[]))->map(fn($f)=>$f->store('inquiries','public'))->all(); DB::transaction(function()use($data,$paths){$inquiry=Inquiry::create([...collect($data)->except(['products','attachments'])->all(),'reference'=>'REQ-'.now()->format('Y').'-'.str_pad((string)(Inquiry::max('id')+1),5,'0',STR_PAD_LEFT),'attachments'=>$paths]); foreach($data['products']??[] as $row){if(empty($row['id']))continue;$p=Product::find($row['id']);$inquiry->items()->create(['product_id'=>$p->id,'description'=>$p->name,'quantity'=>$row['quantity']??1]);}}); return back()->with('success','Your request has been received. Our team will contact you shortly.'); }
    public function quotation(string $token){$q=Quotation::with('items')->where('public_token',$token)->firstOrFail();if(!$q->viewed_at)$q->update(['viewed_at'=>now(),'status'=>$q->status==='sent'?'viewed':$q->status]);return Inertia::render('public/document',['settings'=>BusinessSettings::public(),'document'=>$q,'kind'=>'quotation']);}
    public function respondQuotation(Request $request,string $token){$data=$request->validate(['decision'=>'required|in:accepted,rejected']);$q=Quotation::where('public_token',$token)->firstOrFail();abort_unless(in_array($q->status,['sent','viewed']),422);abort_if($q->expires_at->isPast(),422,'This quotation has expired.');$q->update(['status'=>$data['decision'],'responded_at'=>now()]);return back()->with('success','Your response has been recorded.');}
    public function invoice(string $token){$i=Invoice::with(['items','payments'])->where('public_token',$token)->firstOrFail();if(!$i->viewed_at)$i->update(['viewed_at'=>now(),'status'=>$i->status==='sent'?'viewed':$i->status]);return Inertia::render('public/document',['settings'=>BusinessSettings::public(),'document'=>$i,'kind'=>'invoice']);}
}
