<?php
namespace App\Http\Controllers\Admin;
use App\Http\Controllers\Controller;
use App\Models\{BusinessProfile,Inquiry,Invoice,Payment,Quotation};
use Barryvdh\DomPDF\Facade\Pdf;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Mail;
use Illuminate\Support\Str;
class DocumentController extends Controller {
    private function number(string $type): string {$p=BusinessProfile::first();$prefix=$type==='quote'?($p->quote_prefix??'QTN'):($p->invoice_prefix??'INV');$model=$type==='quote'?Quotation::class:Invoice::class;return $prefix.'-'.now()->format('Y').'-'.str_pad((string)($model::whereYear('created_at',now()->year)->count()+1),5,'0',STR_PAD_LEFT);}
    public function quote(Inquiry $inquiry){$q=DB::transaction(function()use($inquiry){$p=BusinessProfile::first();$q=Quotation::create(['inquiry_id'=>$inquiry->id,'number'=>$this->number('quote'),'customer_name'=>$inquiry->name,'customer_company'=>$inquiry->company,'customer_email'=>$inquiry->email,'customer_phone'=>$inquiry->phone,'issue_date'=>today(),'expires_at'=>today()->addDays($p->quote_valid_days??30),'currency'=>$p->currency??'PKR','public_token'=>Str::uuid(),'business_snapshot'=>$p?->toArray(),'terms'=>'Prices are valid until the expiry date. Installation and delivery are subject to the final scope.']);foreach($inquiry->items as $item)$q->items()->create(['product_id'=>$item->product_id,'description'=>$item->description,'quantity'=>$item->quantity,'unit_price'=>0,'total'=>0]);$inquiry->update(['status'=>'quoted']);return $q;});return redirect()->route('admin.resources.edit',['quotations',$q->id])->with('success','Quotation created. Add pricing, then send it.');}
    public function invoice(Quotation $quotation){abort_unless($quotation->status==='accepted',422,'Only accepted quotations can be invoiced.');$i=DB::transaction(function()use($quotation){$p=BusinessProfile::first();$i=Invoice::create(['quotation_id'=>$quotation->id,'number'=>$this->number('invoice'),'customer_name'=>$quotation->customer_name,'customer_company'=>$quotation->customer_company,'customer_email'=>$quotation->customer_email,'customer_phone'=>$quotation->customer_phone,'issue_date'=>today(),'due_date'=>today()->addDays($p->invoice_due_days??14),'subtotal'=>$quotation->subtotal,'discount'=>$quotation->discount,'tax'=>$quotation->tax,'total'=>$quotation->total,'currency'=>$quotation->currency,'public_token'=>Str::uuid(),'business_snapshot'=>$quotation->business_snapshot,'terms'=>$quotation->terms]);foreach($quotation->items as $x)$i->items()->create($x->only(['product_id','description','quantity','unit_price','tax_rate','total']));return $i;});return redirect()->route('admin.resources.edit',['invoices',$i->id])->with('success','Invoice created.');}
    public function payment(Request $request,Invoice $invoice){$data=$request->validate(['amount'=>'required|numeric|min:0.01','paid_at'=>'required|date','method'=>'required|string','reference'=>'nullable|string','notes'=>'nullable|string']);$invoice->payments()->create([...$data,'recorded_by'=>$request->user()->id]);$paid=$invoice->payments()->whereNull('reversed_at')->sum('amount');$invoice->update(['paid_amount'=>$paid,'status'=>$paid>=$invoice->total?'paid':'partially_paid']);return back()->with('success','Payment recorded.');}
    public function pdf(string $type,int $id){$doc=$type==='quotation'?Quotation::with('items')->findOrFail($id):Invoice::with(['items','payments'])->findOrFail($id);return Pdf::loadView('pdf.document',['document'=>$doc,'type'=>$type])->download($doc->number.'.pdf');}
    public function send(Request $request,string $type,int $id){$doc=$type==='quotation'?Quotation::findOrFail($id):Invoice::findOrFail($id);$data=$request->validate(['subject'=>'required|string|max:190','body'=>'required|string|max:10000']);$url=$type==='quotation'?route('public.quotation',$doc->public_token):route('public.invoice',$doc->public_token);Mail::html(nl2br(e($data['body'])).'<p><a href="'.$url.'">View document</a></p>',fn($m)=>$m->to($doc->customer_email)->subject($data['subject']));$doc->update(['status'=>'sent','sent_at'=>now()]);return back()->with('success','Email sent.');}
}
