<?php
namespace App\Http\Controllers\Admin;
use App\Http\Controllers\Controller;
use App\Jobs\SendDocumentEmail;
use App\Models\{BusinessProfile,EmailMessage,Inquiry,Invoice,Payment,Quotation};
use App\Services\{Audit,DocumentNumber,FinancialCalculator};
use Barryvdh\DomPDF\Facade\Pdf;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;
class DocumentController extends Controller {
    public function quote(Inquiry $inquiry){abort_if($inquiry->status==='spam',422,'Spam requests cannot be quoted.');$q=DB::transaction(function()use($inquiry){$p=BusinessProfile::firstOrFail();$q=Quotation::create(['inquiry_id'=>$inquiry->id,'number'=>DocumentNumber::next('quotation',$p->quote_prefix),'customer_name'=>$inquiry->name,'customer_company'=>$inquiry->company,'customer_email'=>$inquiry->email,'customer_phone'=>$inquiry->phone,'issue_date'=>today(),'expires_at'=>today()->addDays($p->quote_valid_days),'currency'=>$p->currency,'public_token'=>Str::uuid(),'business_snapshot'=>$p->toArray(),'terms'=>'Prices are valid until the expiry date. Installation and delivery are subject to the final scope.']);foreach($inquiry->items as $item)$q->items()->create(['product_id'=>$item->product_id,'description'=>$item->description,'quantity'=>$item->quantity,'unit_price'=>0,'tax_rate'=>0,'total'=>0]);$inquiry->update(['status'=>'quoted']);Audit::record('quotation.created',$q);return $q;});return redirect()->route('admin.resources.edit',['quotations',$q->id])->with('success','Quotation created. Add pricing, then send it.');}
    public function updateQuotation(Request $request,Quotation $quotation){abort_unless($quotation->status==='draft',422,'Only draft quotations can be edited.');$data=$request->validate(['customer_name'=>'required|string|max:190','customer_company'=>'nullable|string|max:190','customer_email'=>'required|email|max:190','customer_phone'=>'nullable|string|max:50','expires_at'=>'required|date|after_or_equal:today','discount'=>'nullable|numeric|min:0','notes'=>'nullable|string|max:10000','terms'=>'nullable|string|max:20000','items'=>'required|array|min:1|max:100','items.*.product_id'=>'nullable|exists:products,id','items.*.description'=>'required|string|max:500','items.*.quantity'=>'required|numeric|min:0.01|max:100000','items.*.unit_price'=>'required|numeric|min:0|max:999999999999.99','items.*.tax_rate'=>'nullable|numeric|min:0|max:100']);$totals=FinancialCalculator::totals($data['items'],(float)($data['discount']??0));DB::transaction(function()use($quotation,$data,$totals){$before=$quotation->toArray();$quotation->update([...collect($data)->except('items')->all(),...collect($totals)->except('items')->all()]);$quotation->items()->delete();foreach($totals['items'] as $item)$quotation->items()->create($item);Audit::record('quotation.updated',$quotation,$before,$quotation->fresh()->toArray());});return back()->with('success','Quotation recalculated and saved.');}
    public function invoice(Quotation $quotation){abort_unless($quotation->status==='accepted',422,'Only accepted quotations can be invoiced.');abort_if($quotation->invoice()->exists(),422,'This quotation has already been invoiced.');abort_if($quotation->total<=0,422,'A zero-value quotation cannot be invoiced.');$i=DB::transaction(function()use($quotation){$p=BusinessProfile::firstOrFail();$i=Invoice::create(['quotation_id'=>$quotation->id,'number'=>DocumentNumber::next('invoice',$p->invoice_prefix),'customer_name'=>$quotation->customer_name,'customer_company'=>$quotation->customer_company,'customer_email'=>$quotation->customer_email,'customer_phone'=>$quotation->customer_phone,'issue_date'=>today(),'due_date'=>today()->addDays($p->invoice_due_days),'subtotal'=>$quotation->subtotal,'discount'=>$quotation->discount,'tax'=>$quotation->tax,'total'=>$quotation->total,'currency'=>$quotation->currency,'public_token'=>Str::uuid(),'business_snapshot'=>$quotation->business_snapshot,'terms'=>$quotation->terms]);foreach($quotation->items as $x)$i->items()->create($x->only(['product_id','description','quantity','unit_price','tax_rate','total']));Audit::record('invoice.created',$i);return $i;});return redirect()->route('admin.resources.edit',['invoices',$i->id])->with('success','Invoice created.');}
    public function payment(Request $request,Invoice $invoice){abort_if(in_array($invoice->status,['void','paid']),422,'Payments cannot be added to this invoice.');$data=$request->validate(['amount'=>'required|numeric|min:0.01','paid_at'=>'required|date|before_or_equal:today','method'=>'required|in:bank,cash,cheque,other','reference'=>'nullable|string|max:190','notes'=>'nullable|string|max:5000']);return DB::transaction(function()use($request,$invoice,$data){$invoice=Invoice::lockForUpdate()->findOrFail($invoice->id);$balance=round((float)$invoice->total-(float)$invoice->payments()->whereNull('reversed_at')->sum('amount'),2);abort_if((float)$data['amount']>$balance,422,'Payment exceeds the outstanding balance.');$payment=$invoice->payments()->create([...$data,'recorded_by'=>$request->user()->id]);$this->syncPaymentStatus($invoice);Audit::record('payment.recorded',$payment);return back()->with('success','Payment recorded.');});}
    public function reversePayment(Request $request,Payment $payment){$data=$request->validate(['reason'=>'required|string|max:2000']);abort_if($payment->reversed_at,422,'This payment has already been reversed.');DB::transaction(function()use($request,$payment,$data){$payment->update(['reversed_at'=>now(),'reversed_by'=>$request->user()->id,'reversal_reason'=>$data['reason']]);$this->syncPaymentStatus($payment->invoice()->lockForUpdate()->firstOrFail());Audit::record('payment.reversed',$payment,[],['reason'=>$data['reason']]);});return back()->with('success','Payment reversed.');}
    public function voidInvoice(Request $request,Invoice $invoice){$data=$request->validate(['reason'=>'required|string|max:2000']);abort_if($invoice->payments()->whereNull('reversed_at')->exists(),422,'Reverse active payments before voiding the invoice.');abort_if($invoice->status==='void',422,'Invoice is already void.');$before=$invoice->only('status');$invoice->update(['status'=>'void','void_reason'=>$data['reason'],'voided_at'=>now()]);Audit::record('invoice.voided',$invoice,$before,$invoice->only('status','void_reason'));return back()->with('success','Invoice voided.');}
    public function pdf(string $type,int $id){$doc=$type==='quotation'?Quotation::with('items')->findOrFail($id):Invoice::with(['items','payments'])->findOrFail($id);return Pdf::loadView('pdf.document',['document'=>$doc,'type'=>$type])->download($doc->number.'.pdf');}
    public function send(Request $request,string $type,int $id){abort_unless(in_array($type,['quotation','invoice']),404);$doc=$type==='quotation'?Quotation::with('items')->findOrFail($id):Invoice::with('items')->findOrFail($id);abort_if($doc->total<=0,422,'A zero-value document cannot be sent.');abort_if(in_array($doc->status,['accepted','rejected','expired','superseded','paid','void']),422,'This document can no longer be sent.');$data=$request->validate(['subject'=>'required|string|max:190','body'=>'required|string|max:10000']);$message=$doc->emailMessages()->create(['user_id'=>$request->user()->id,'to'=>$doc->customer_email,'subject'=>$data['subject'],'body'=>$data['body'],'status'=>'queued']);SendDocumentEmail::dispatch($message->id)->afterCommit();Audit::record('email.queued',$doc,[],['email_message_id'=>$message->id]);return back()->with('success','Email queued for delivery.');}
    private function syncPaymentStatus(Invoice $invoice): void {$paid=round((float)$invoice->payments()->whereNull('reversed_at')->sum('amount'),2);$wasIssued=$invoice->sent_at||in_array($invoice->status,['sent','viewed','partially_paid','paid'])||$invoice->payments()->exists();$unpaidStatus=$invoice->status==='overdue'?'overdue':($wasIssued?'sent':'draft');$status=$paid<=0?$unpaidStatus:($paid>=(float)$invoice->total?'paid':'partially_paid');$invoice->update(['paid_amount'=>$paid,'status'=>$status]);}
}
