<?php
namespace App\Http\Controllers\Admin;
use App\Http\Controllers\Controller;
use App\Models\{BankAccount,BusinessProfile,Category,ContactChannel,ContentPage,Inquiry,Invoice,OfficeLocation,Payment,Product,Quotation,SocialLink,User};
use App\Services\BusinessSettings;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Facades\Storage;
use Illuminate\Support\Str;
use Inertia\Inertia;
class ResourceController extends Controller {
    private function definitions(): array { return [
        'products'=>['model'=>Product::class,'title'=>'Products','columns'=>['name','sku','brand','price_mode','price','is_published'],'fields'=>['name'=>'text','slug'=>'text','sku'=>'text','brand'=>'text','category_id'=>'relation:categories','summary'=>'textarea','description'=>'textarea','images'=>'images','price'=>'number','price_mode'=>'select:quote,visible,hidden','is_featured'=>'boolean','is_published'=>'boolean']],
        'categories'=>['model'=>Category::class,'title'=>'Categories','columns'=>['name','slug','is_active','sort_order'],'fields'=>['name'=>'text','slug'=>'text','parent_id'=>'relation:categories','description'=>'textarea','images'=>'images','is_active'=>'boolean','sort_order'=>'number']],
        'pages'=>['model'=>ContentPage::class,'title'=>'Content','columns'=>['title','type','slug','is_published'],'fields'=>['title'=>'text','slug'=>'text','type'=>'select:page,solution,project,news,career,certification,brand','eyebrow'=>'text','excerpt'=>'textarea','body'=>'textarea','image_url'=>'text','is_published'=>'boolean','sort_order'=>'number']],
        'business'=>['model'=>BusinessProfile::class,'title'=>'Business profile','columns'=>['name','legal_name','currency','default_tax_rate'],'fields'=>['name'=>'text','legal_name'=>'text','tagline'=>'text','description'=>'textarea','currency'=>'text','default_tax_rate'=>'number','quote_valid_days'=>'number','invoice_due_days'=>'number','quote_prefix'=>'text','invoice_prefix'=>'text','tax_number'=>'text','registration_number'=>'text','email_from_name'=>'text','footer_text'=>'textarea']],
        'locations'=>['model'=>OfficeLocation::class,'title'=>'Locations','columns'=>['name','city','country','is_primary','is_active'],'fields'=>['name'=>'text','address_line_1'=>'text','address_line_2'=>'text','city'=>'text','region'=>'text','postal_code'=>'text','country'=>'text','map_url'=>'text','hours'=>'text','is_primary'=>'boolean','is_active'=>'boolean','sort_order'=>'number']],
        'contacts'=>['model'=>ContactChannel::class,'title'=>'Contact channels','columns'=>['label','type','value','is_primary','is_public'],'fields'=>['office_location_id'=>'number','type'=>'select:email,phone,mobile,whatsapp,fax','label'=>'text','value'=>'text','is_primary'=>'boolean','is_public'=>'boolean','sort_order'=>'number']],
        'social-links'=>['model'=>SocialLink::class,'title'=>'Social links','columns'=>['platform','url','is_active','sort_order'],'fields'=>['platform'=>'text','url'=>'text','icon'=>'text','is_active'=>'boolean','sort_order'=>'number']],
        'bank-accounts'=>['model'=>BankAccount::class,'title'=>'Bank accounts','columns'=>['bank_name','account_title','account_number','is_active'],'fields'=>['bank_name'=>'text','account_title'=>'text','account_number'=>'text','iban'=>'text','branch'=>'text','instructions'=>'textarea','is_active'=>'boolean','sort_order'=>'number']],
        'inquiries'=>['model'=>Inquiry::class,'title'=>'Requests','columns'=>['reference','name','company','email','status','created_at'],'fields'=>['status'=>'select:new,assigned,contacted,quoted,won,lost,closed,spam','assigned_to'=>'number','subject'=>'text','message'=>'textarea']],
        'quotations'=>['model'=>Quotation::class,'title'=>'Quotations','columns'=>['number','customer_name','customer_company','total','status','expires_at'],'fields'=>['status'=>'select:draft,sent,viewed,accepted,rejected,expired,superseded','notes'=>'textarea','terms'=>'textarea']],
        'invoices'=>['model'=>Invoice::class,'title'=>'Invoices','columns'=>['number','customer_name','total','paid_amount','status','due_date'],'fields'=>['status'=>'select:draft,sent,viewed,partially_paid,paid,overdue,void','notes'=>'textarea','terms'=>'textarea']],
        'payments'=>['model'=>Payment::class,'title'=>'Payments','columns'=>['invoice_id','amount','paid_at','method','reference'],'fields'=>['invoice_id'=>'number','amount'=>'number','paid_at'=>'date','method'=>'select:bank,cash,cheque,other','reference'=>'text','notes'=>'textarea']],
        'users'=>['model'=>User::class,'title'=>'Administrators','columns'=>['name','email','is_active','created_at'],'fields'=>['name'=>'text','email'=>'email','password'=>'password','role'=>'select:Super Admin,Sales,Accounts,Catalog Manager,Content Editor,Support','is_active'=>'boolean']],
    ]; }
    private function def(string $resource): array { return $this->definitions()[$resource] ?? abort(404); }
    public function index(Request $request,string $resource){$d=$this->def($resource);$q=$d['model']::query();if($request->search){$first=array_key_first($d['fields']);$q->where($first,'like','%'.$request->search.'%');}return Inertia::render('admin/resources/index',['resource'=>$resource,'title'=>$d['title'],'columns'=>$d['columns'],'fields'=>$d['fields'],'records'=>$q->latest()->paginate(20)->withQueryString()]);}
    public function create(string $resource){$d=$this->def($resource);return Inertia::render('admin/resources/form',['resource'=>$resource,'title'=>'New '.$d['title'],'fields'=>$d['fields'],'record'=>null,'options'=>$this->options($resource)]);}
    public function edit(string $resource,int $id){$d=$this->def($resource);$record=$d['model']::findOrFail($id);if($resource==='users')$record->setAttribute('role',$record->getRoleNames()->first());return Inertia::render('admin/resources/form',['resource'=>$resource,'title'=>'Edit '.$d['title'],'fields'=>$d['fields'],'record'=>$record,'options'=>$this->options($resource,$id)]);}
    public function store(Request $request,string $resource){$d=$this->def($resource);$data=$this->clean($request,$d['fields']);$role=$data['role']??null;unset($data['role']);if(isset($data['slug'])&&blank($data['slug']))$data['slug']=Str::slug($data['name']??$data['title']);if($resource==='users'&&empty($data['password']))$data['password']=Hash::make(Str::password(20));$model=$d['model']::create($data);$this->manageImages($request,$model,$resource);if($resource==='users'&&$role)$model->syncRoles([$role]);BusinessSettings::forget();return redirect()->route('admin.resources.index',$resource)->with('success','Created successfully.');}
    public function update(Request $request,string $resource,int $id){$d=$this->def($resource);$model=$d['model']::findOrFail($id);$data=$this->clean($request,$d['fields']);$role=$data['role']??null;unset($data['role']);if($resource==='users'&&empty($data['password']))unset($data['password']);$model->update($data);$this->manageImages($request,$model,$resource);if($resource==='users'&&$role)$model->syncRoles([$role]);BusinessSettings::forget();return redirect()->route('admin.resources.index',$resource)->with('success','Updated successfully.');}
    public function destroy(string $resource,int $id){$d=$this->def($resource);$d['model']::findOrFail($id)->delete();BusinessSettings::forget();return back()->with('success','Deleted successfully.');}
    private function clean(Request $request,array $fields): array {$data=[];foreach($fields as $name=>$type){$base=strtok($type,':');if($base==='images')continue;if($name==='category_id')$request->validate(['category_id'=>'nullable|exists:categories,id']);if($name==='parent_id')$request->validate(['parent_id'=>'nullable|exists:categories,id']);if($base==='boolean')$data[$name]=$request->boolean($name);elseif($request->has($name))$data[$name]=$request->input($name)?:null;}return $data;}
    private function options(string $resource,?int $id=null): array {if(!in_array($resource,['products','categories']))return [];return ['categories'=>Category::when($resource==='categories'&&$id,fn($q)=>$q->whereKeyNot($id))->orderBy('name')->get(['id','name'])];}
    private function manageImages(Request $request,Model $model,string $resource): void {if(!in_array($resource,['products','categories']))return;$request->validate(['new_images'=>'nullable|array|max:12','new_images.*'=>'image|mimes:jpg,jpeg,png,webp|max:5120','remove_images'=>'nullable|array','remove_images.*'=>'integer|min:0','thumbnail_index'=>'nullable|integer|min:0']);$existing=collect($model->images??[]);$selected=$existing->get((int)$request->input('thumbnail_index',0));$removed=$request->input('remove_images',[]);$existing->only($removed)->each(fn($path)=>str_starts_with($path,'/storage/')&&Storage::disk('public')->delete(str($path)->after('/storage/')));$images=$existing->reject(fn($v,$i)=>in_array($i,$removed))->values();foreach($request->file('new_images',[]) as $file)$images->push('/storage/'.$file->store('catalog/'.$resource,'public'));$thumbnail=$selected?$images->search($selected,true):0;$model->update(['images'=>$images->all(),'thumbnail_index'=>$thumbnail===false?0:$thumbnail]);}
}
