<?php
namespace App\Http\Controllers\Admin;
use App\Http\Controllers\Controller;
use App\Models\{BankAccount,BusinessProfile,Category,ContactChannel,ContentPage,Inquiry,Invoice,OfficeLocation,Payment,Product,Quotation,SocialLink,User};
use App\Services\BusinessSettings;
use App\Services\Audit;
use App\Services\DocumentNumber;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\DB;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Facades\Password;
use Illuminate\Support\Facades\Storage;
use Illuminate\Support\Str;
use Illuminate\Validation\Rule;
use Illuminate\Validation\ValidationException;
use Inertia\Inertia;
class ResourceController extends Controller {
    private function definitions(): array { return [
        'products'=>['model'=>Product::class,'title'=>'Products','columns'=>['name','sku','brand','price_mode','price','is_published'],'fields'=>['name'=>'text','slug'=>'text','sku'=>'text','brand'=>'text','category_id'=>'relation:categories','summary'=>'textarea','description'=>'textarea','specifications'=>'specifications','images'=>'images','image_alt'=>'text','brochure_url'=>'file:pdf','price'=>'number','price_mode'=>'select:quote,visible,hidden','seo_title'=>'text','seo_description'=>'textarea','is_featured'=>'boolean','is_published'=>'boolean']],
        'categories'=>['model'=>Category::class,'title'=>'Categories','columns'=>['name','slug','is_active','sort_order'],'fields'=>['name'=>'text','slug'=>'text','parent_id'=>'relation:categories','description'=>'textarea','images'=>'images','image_alt'=>'text','seo_title'=>'text','seo_description'=>'textarea','is_active'=>'boolean','sort_order'=>'number']],
        'pages'=>['model'=>ContentPage::class,'title'=>'Content pages','columns'=>['title','type','slug','is_published','sort_order'],'fields'=>['type'=>'select:page,solution,project,news','title'=>'text','slug'=>'text','eyebrow'=>'text','excerpt'=>'textarea','body'=>'textarea','image_url'=>'file:image','image_alt'=>'text','seo_title'=>'text','seo_description'=>'textarea','publish_at'=>'datetime-local','is_published'=>'boolean','sort_order'=>'number']],
        'business'=>['model'=>BusinessProfile::class,'title'=>'Business profile','columns'=>['name','legal_name','currency','default_tax_rate'],'fields'=>['name'=>'text','legal_name'=>'text','tagline'=>'text','description'=>'textarea','logo_path'=>'file:image','currency'=>'text','default_tax_rate'=>'number','quote_valid_days'=>'number','invoice_due_days'=>'number','quote_prefix'=>'text','invoice_prefix'=>'text','tax_number'=>'text','registration_number'=>'text','email_from_name'=>'text','footer_text'=>'textarea']],
        'locations'=>['model'=>OfficeLocation::class,'title'=>'Locations','columns'=>['name','city','country','is_primary','is_active'],'fields'=>['name'=>'text','address_line_1'=>'text','address_line_2'=>'text','city'=>'text','region'=>'text','postal_code'=>'text','country'=>'text','map_url'=>'text','hours'=>'text','is_primary'=>'boolean','is_active'=>'boolean','sort_order'=>'number']],
        'contacts'=>['model'=>ContactChannel::class,'title'=>'Contact channels','columns'=>['label','type','value','is_primary','is_public'],'fields'=>['office_location_id'=>'relation:locations','type'=>'select:email,phone,mobile,whatsapp,fax','label'=>'text','value'=>'contact-value','is_primary'=>'boolean','is_public'=>'boolean','sort_order'=>'number']],
        'social-links'=>['model'=>SocialLink::class,'title'=>'Social links','columns'=>['platform','url','is_active','sort_order'],'fields'=>['platform'=>'text','url'=>'text','icon'=>'text','is_active'=>'boolean','sort_order'=>'number']],
        'bank-accounts'=>['model'=>BankAccount::class,'title'=>'Bank accounts','columns'=>['bank_name','account_title','account_number','is_active'],'fields'=>['bank_name'=>'text','account_title'=>'text','account_number'=>'text','iban'=>'text','branch'=>'text','instructions'=>'textarea','is_active'=>'boolean','sort_order'=>'number']],
        'inquiries'=>['model'=>Inquiry::class,'title'=>'Requests','columns'=>['reference','name','company','email','status','created_at'],'fields'=>['type'=>'select:general,quote','name'=>'text','company'=>'text','email'=>'email','phone'=>'text','city'=>'text','subject'=>'text','message'=>'textarea','internal_notes'=>'textarea','attachments'=>'files:inquiry','status'=>'select:new,assigned,contacted,quoted,won,lost,closed,spam','assigned_to'=>'relation:users','products'=>'product-lines']],
        'quotations'=>['model'=>Quotation::class,'title'=>'Quotations','columns'=>['number','customer_name','customer_company','total','status','expires_at'],'fields'=>['status'=>'select:draft,sent,viewed,accepted,rejected,expired,superseded','notes'=>'textarea','terms'=>'textarea']],
        'invoices'=>['model'=>Invoice::class,'title'=>'Invoices','columns'=>['number','customer_name','total','paid_amount','status','due_date'],'fields'=>['status'=>'select:draft,sent,viewed,partially_paid,paid,overdue,void','notes'=>'textarea','terms'=>'textarea']],
        'payments'=>['model'=>Payment::class,'title'=>'Payments','columns'=>['invoice_id','amount','paid_at','method','reference'],'fields'=>['invoice_id'=>'number','amount'=>'number','paid_at'=>'date','method'=>'select:bank,cash,cheque,other','reference'=>'text','notes'=>'textarea']],
        'users'=>['model'=>User::class,'title'=>'Administrators','columns'=>['name','email','is_active','created_at'],'fields'=>['name'=>'text','email'=>'email','role'=>'select:Super Admin,Sales,Accounts,Catalog Manager,Content Editor,Support','is_active'=>'boolean']],
    ]; }
    private function def(string $resource): array { return $this->definitions()[$resource] ?? abort(404); }
    public function index(Request $request,string $resource){$this->authorizeResource($request,$resource);$d=$this->def($resource);$q=$d['model']::query();$validated=$request->validate(['search'=>'nullable|string|max:100']);$search=trim((string)($validated['search']??''));if($search!==''){$first=array_key_first($d['fields']);$q->where($first,'like','%'.$search.'%');}return Inertia::render('admin/resources/index',['resource'=>$resource,'title'=>$d['title'],'columns'=>$d['columns'],'fields'=>$d['fields'],'records'=>$q->latest()->paginate(20)->withQueryString()]);}
    public function create(Request $request,string $resource){$this->authorizeResource($request,$resource);abort_if($resource==='business'&&BusinessProfile::exists(),422,'Only one business profile is allowed.');$d=$this->def($resource);return Inertia::render('admin/resources/form',['resource'=>$resource,'title'=>'New '.$d['title'],'fields'=>$d['fields'],'record'=>null,'options'=>$this->options($resource)]);}
    public function edit(Request $request,string $resource,int $id){$this->authorizeResource($request,$resource);$d=$this->def($resource);$record=$d['model']::findOrFail($id);if($resource==='users')$record->setAttribute('role',$record->getRoleNames()->first());if($resource==='inquiries')$record->load('items');if($resource==='quotations')$record->load('items');if($resource==='invoices')$record->load(['items','payments']);if($resource==='payments')$record->load('invoice');return Inertia::render('admin/resources/form',['resource'=>$resource,'title'=>'Edit '.$d['title'],'fields'=>$d['fields'],'record'=>$record,'options'=>$this->options($resource,$id)]);}
    public function store(Request $request,string $resource){$this->authorizeResource($request,$resource);abort_if($resource==='business'&&BusinessProfile::exists(),422,'Only one business profile is allowed.');abort_if(in_array($resource,['quotations','invoices','payments']),422,'Use the controlled workflow to create financial records.');$d=$this->def($resource);$request->validate($this->rules($resource));$data=$this->clean($request,$d['fields']);$role=$data['role']??null;unset($data['role']);if(array_key_exists('slug',$data)&&blank($data['slug']))$data['slug']=Str::slug($data['name']??$data['title']);if($resource==='users'){$data['password']=Hash::make(Str::password(32));$data['invited_at']=now();}$model=DB::transaction(function()use($request,$resource,$d,$data){if($resource==='inquiries')$data['reference']=DocumentNumber::next('inquiry','REQ');$model=$d['model']::create($data);if($resource==='inquiries')$this->syncInquiryItems($model,$request->input('products',[]));return $model;});$this->manageImages($request,$model,$resource);$this->manageUploads($request,$model,$resource);if($resource==='users'&&$role){$model->syncRoles([$role]);Password::sendResetLink(['email'=>$model->email]);}Audit::record($resource.'.created',$model);BusinessSettings::forget();return redirect()->route('admin.resources.index',$resource)->with('success',$resource==='users'?'Administrator invited by email.':'Created successfully.');}
    public function update(Request $request,string $resource,int $id){$this->authorizeResource($request,$resource);$d=$this->def($resource);$model=$d['model']::findOrFail($id);$request->validate($this->rules($resource,$model));$data=$this->clean($request,$d['fields']);$role=$data['role']??null;unset($data['role']);if(array_key_exists('slug',$data)&&blank($data['slug']))$data['slug']=Str::slug($data['name']??$data['title']);if(in_array($resource,['quotations','invoices'])&&isset($data['status'])&&$data['status']!==$model->status)throw ValidationException::withMessages(['status'=>'Document status is controlled by its workflow.']);if($resource==='payments')throw ValidationException::withMessages(['amount'=>'Posted payments cannot be edited.']);if($resource==='users'&&$model->is($request->user())&&array_key_exists('is_active',$data)&&!$data['is_active'])throw ValidationException::withMessages(['is_active'=>'You cannot disable your own account.']);$before=$model->toArray();DB::transaction(function()use($request,$resource,$model,$data){$model->update($data);if($resource==='inquiries')$this->syncInquiryItems($model,$request->input('products',[]));});$this->manageImages($request,$model,$resource);$this->manageUploads($request,$model,$resource);if($resource==='users'&&$role)$model->syncRoles([$role]);Audit::record($resource.'.updated',$model,$before,$model->fresh()->toArray());BusinessSettings::forget();return redirect()->route('admin.resources.index',$resource)->with('success','Updated successfully.');}
    public function destroy(Request $request,string $resource,int $id){$this->authorizeResource($request,$resource);$d=$this->def($resource);$model=$d['model']::findOrFail($id);abort_if($resource==='business',422,'The business profile cannot be deleted.');abort_if($resource==='users'&&$model->is($request->user()),422,'You cannot delete your own account.');abort_if($resource==='users'&&$model->hasRole('Super Admin')&&User::role('Super Admin')->count()<=1,422,'The final Super Admin cannot be deleted.');abort_if(in_array($resource,['quotations','invoices','payments'])&&$model->exists,422,'Financial records cannot be deleted; use the controlled void or reversal workflow.');Audit::record($resource.'.deleted',$model,$model->toArray());$model->delete();BusinessSettings::forget();return back()->with('success','Deleted successfully.');}
    public function inquiryAttachment(Request $request, Inquiry $inquiry, int $index){$this->authorizeResource($request,'inquiries');$path=collect($inquiry->attachments)->get($index);abort_unless($path&&Storage::disk('local')->exists($path),404);return Storage::disk('local')->download($path,basename($path));}
    private function clean(Request $request,array $fields): array {$data=[];foreach($fields as $name=>$type){$base=strtok($type,':');if(in_array($base,['images','product-lines','file','files']))continue;if($name==='category_id')$request->validate(['category_id'=>'nullable|exists:categories,id']);if($name==='parent_id')$request->validate(['parent_id'=>'nullable|exists:categories,id']);if($base==='boolean')$data[$name]=$request->boolean($name);elseif($base==='specifications')$data[$name]=collect($request->input($name,[]))->filter(fn($row)=>filled($row['key']??null))->mapWithKeys(fn($row)=>[$row['key']=>$row['value']??''])->all();elseif($name==='sort_order')$data[$name]=$request->filled($name)?(int)$request->input($name):0;elseif($request->has($name))$data[$name]=$request->input($name)?:null;}return $data;}
    private function options(string $resource,?int $id=null): array {if($resource==='inquiries')return ['products'=>Product::where('is_published',true)->orderBy('name')->get(['id','name','sku']),'users'=>User::where('is_active',true)->orderBy('name')->get(['id','name'])];if($resource==='contacts')return ['locations'=>OfficeLocation::where('is_active',true)->orderBy('name')->get(['id','name'])];if(!in_array($resource,['products','categories','quotations']))return [];return ['categories'=>Category::when($resource==='categories'&&$id,fn($q)=>$q->whereKeyNot($id))->orderBy('name')->get(['id','name']),'products'=>Product::where('is_published',true)->orderBy('name')->get(['id','name','sku'])];}
    private function syncInquiryItems(Inquiry $inquiry,array $rows): void {$inquiry->items()->delete();foreach($rows as $row){$product=Product::findOrFail($row['product_id']);$inquiry->items()->create(['product_id'=>$product->id,'description'=>$product->name,'quantity'=>$row['quantity']]);}}
    private function manageImages(Request $request,Model $model,string $resource): void {if(!in_array($resource,['products','categories']))return;$request->validate(['new_images'=>'nullable|array|max:12','new_images.*'=>'image|mimes:jpg,jpeg,png,webp|max:5120','remove_images'=>'nullable|array','remove_images.*'=>'integer|min:0','thumbnail_index'=>'nullable|integer|min:0']);$existing=collect($model->images??[]);$selectedIndex=(int)$request->input('thumbnail_index',0);$removed=$request->input('remove_images',[]);$selectedPath=$selectedIndex<$existing->count()?$existing->get($selectedIndex):null;$selectedUpload=$selectedIndex-$existing->count();$existing->only($removed)->each(fn($path)=>str_starts_with($path,'/storage/')&&Storage::disk('public')->delete(str($path)->after('/storage/')));$images=$existing->reject(fn($v,$i)=>in_array($i,$removed))->values();$uploaded=[];foreach($request->file('new_images',[]) as $file){$path='/storage/'.$file->store('catalog/'.$resource,'public');$uploaded[]=$path;$images->push($path);}$thumbnail=$selectedPath?$images->search($selectedPath,true):(($selectedUpload>=0&&isset($uploaded[$selectedUpload]))?$images->search($uploaded[$selectedUpload],true):0);$model->update(['images'=>$images->all(),'thumbnail_index'=>$thumbnail===false?0:$thumbnail]);}
    private function manageUploads(Request $request,Model $model,string $resource): void {if($resource==='products'&&$request->hasFile('brochure_url')){$old=$model->brochure_url;if($old&&str_starts_with($old,'/storage/'))Storage::disk('public')->delete(str($old)->after('/storage/'));$model->update(['brochure_url'=>'/storage/'.$request->file('brochure_url')->store('catalog/brochures','public')]);}if($resource==='pages'&&$request->hasFile('image_url')){$model->update(['image_url'=>'/storage/'.$request->file('image_url')->store('content','public')]);}if($resource==='business'&&$request->hasFile('logo_path')){$model->update(['logo_path'=>'/storage/'.$request->file('logo_path')->store('business','public')]);}if($resource==='inquiries'&&$request->hasFile('attachments')){$paths=collect($model->attachments??[]);foreach($request->file('attachments') as $file)$paths->push($file->store('inquiries','local'));$model->update(['attachments'=>$paths->all()]);}}

    private function authorizeResource(Request $request,string $resource): void
    {
        $permission = match ($resource) {
            'products', 'categories' => 'products.manage',
            'pages' => 'content.manage',
            'business', 'locations', 'contacts', 'social-links', 'bank-accounts' => 'business.manage',
            'inquiries' => 'inquiries.manage',
            'quotations' => 'quotations.manage',
            'invoices' => 'invoices.manage',
            'payments' => 'payments.manage',
            'users' => 'users.manage',
            default => abort(404),
        };
        abort_unless($request->user()?->can($permission),403);
    }

    private function rules(string $resource, ?Model $model=null): array
    {
        $id=$model?->getKey();
        return match($resource){
            'products'=>['name'=>'required|string|max:190','slug'=>['nullable','string','max:190',Rule::unique('products','slug')->ignore($id)],'sku'=>['nullable','string','max:100',Rule::unique('products','sku')->ignore($id)],'brand'=>'nullable|string|max:150','category_id'=>'nullable|exists:categories,id','summary'=>'nullable|string|max:1000','description'=>'nullable|string|max:50000','specifications'=>'nullable|array|max:100','specifications.*.key'=>'required|string|max:190','specifications.*.value'=>'nullable|string|max:1000','new_images'=>'nullable|array|max:12','new_images.*'=>'image|mimes:jpg,jpeg,png,webp|max:5120','image_alt'=>'nullable|string|max:255','brochure_url'=>'nullable|file|mimes:pdf|max:20480','price'=>'nullable|numeric|min:0|max:999999999999.99','price_mode'=>'required|in:quote,visible,hidden','seo_title'=>'nullable|string|max:190','seo_description'=>'nullable|string|max:500'],
            'categories'=>['name'=>'required|string|max:190','slug'=>['nullable','string','max:190',Rule::unique('categories','slug')->ignore($id)],'parent_id'=>['nullable','exists:categories,id',Rule::notIn(array_filter([$id]))],'description'=>'nullable|string|max:5000','image_alt'=>'nullable|string|max:255','seo_title'=>'nullable|string|max:190','seo_description'=>'nullable|string|max:500','sort_order'=>'nullable|integer|min:0|max:100000'],
            'pages'=>['type'=>'required|in:page,solution,project,news','title'=>'required|string|max:190','slug'=>['nullable','string','max:190',Rule::unique('content_pages','slug')->ignore($id)],'eyebrow'=>'nullable|string|max:255','excerpt'=>'nullable|string|max:2000','body'=>'nullable|string|max:100000','image_url'=>'nullable|image|mimes:jpg,jpeg,png,webp,svg|max:5120','image_alt'=>'nullable|string|max:255','seo_title'=>'nullable|string|max:190','seo_description'=>'nullable|string|max:500','publish_at'=>'nullable|date','sort_order'=>'nullable|integer|min:0|max:100000'],
            'business'=>['name'=>'required|string|max:190','legal_name'=>'nullable|string|max:190','tagline'=>'nullable|string|max:255','description'=>'nullable|string|max:5000','logo_path'=>'nullable|image|mimes:jpg,jpeg,png,webp,svg|max:5120','currency'=>'required|string|size:3','default_tax_rate'=>'required|numeric|min:0|max:100','quote_valid_days'=>'required|integer|min:1|max:365','invoice_due_days'=>'required|integer|min:0|max:365','quote_prefix'=>'required|string|max:20','invoice_prefix'=>'required|string|max:20','tax_number'=>'nullable|string|max:100','registration_number'=>'nullable|string|max:100','email_from_name'=>'nullable|string|max:190','footer_text'=>'nullable|string|max:2000'],
            'locations'=>['name'=>'required|string|max:190','address_line_1'=>'required|string|max:255','address_line_2'=>'nullable|string|max:255','city'=>'required|string|max:100','region'=>'nullable|string|max:100','postal_code'=>'nullable|string|max:30','country'=>'required|string|max:100','map_url'=>'nullable|url|max:2048','hours'=>'nullable|string|max:255','sort_order'=>'nullable|integer|min:0|max:100000'],
            'contacts'=>['office_location_id'=>'nullable|exists:office_locations,id','type'=>'required|in:email,phone,mobile,whatsapp,fax','label'=>'required|string|max:100','value'=>['required','string','max:255',function($attribute,$value,$fail){if(request()->input('type')==='email'&&!filter_var($value,FILTER_VALIDATE_EMAIL))$fail('Enter a valid email address.');if(request()->input('type')!=='email'&&!preg_match('/^[0-9+()\-\s]{5,30}$/',$value))$fail('Enter a valid phone or fax number.');}],'sort_order'=>'nullable|integer|min:0|max:100000'],
            'social-links'=>['platform'=>'required|string|max:100','url'=>'required|url|max:2048','icon'=>'nullable|string|max:100','sort_order'=>'nullable|integer|min:0|max:100000'],
            'bank-accounts'=>['bank_name'=>'required|string|max:190','account_title'=>'required|string|max:190','account_number'=>'nullable|string|max:100','iban'=>'nullable|string|max:50','branch'=>'nullable|string|max:190','instructions'=>'nullable|string|max:2000','sort_order'=>'nullable|integer|min:0|max:100000'],
            'inquiries'=>['type'=>'required|in:general,quote','name'=>'required|string|max:150','company'=>'nullable|string|max:150','email'=>'required|email|max:190','phone'=>'nullable|string|max:50','city'=>'nullable|string|max:100','subject'=>'nullable|string|max:190','message'=>'required|string|max:5000','internal_notes'=>'nullable|string|max:20000','attachments'=>'nullable|array|max:10','attachments.*'=>'file|mimes:pdf,jpg,jpeg,png,doc,docx,xls,xlsx|max:20480','status'=>'required|in:new,assigned,contacted,quoted,won,lost,closed,spam','assigned_to'=>'nullable|exists:users,id','products'=>'nullable|array|max:50','products.*.product_id'=>'required|distinct|exists:products,id','products.*.quantity'=>'required|numeric|min:0.01|max:100000'],
            'quotations'=>['status'=>'required|in:draft,sent,viewed,accepted,rejected,expired,superseded','notes'=>'nullable|string|max:10000','terms'=>'nullable|string|max:20000'],
            'invoices'=>['status'=>'required|in:draft,sent,viewed,partially_paid,paid,overdue,void','notes'=>'nullable|string|max:10000','terms'=>'nullable|string|max:20000'],
            'payments'=>['invoice_id'=>'required|exists:invoices,id','amount'=>'required|numeric|min:0.01|max:999999999999.99','paid_at'=>'required|date|before_or_equal:today','method'=>'required|in:bank,cash,cheque,other','reference'=>'nullable|string|max:190','notes'=>'nullable|string|max:5000'],
            'users'=>['name'=>'required|string|max:190','email'=>['required','email','max:190',Rule::unique('users','email')->ignore($id)],'password'=>['nullable','string','min:12','max:255'],'role'=>'required|in:Super Admin,Sales,Accounts,Catalog Manager,Content Editor,Support'],
        };
    }
}
