import BrandLogo from '@/components/brand-logo';
import { Link, router, usePage } from '@inertiajs/react';

export default function AdminLayout({ children, title }: { children: React.ReactNode; title: string }) {
    const page=usePage<any>();
    const permissions:string[]=page.props.auth.user?.permissions||[];
    const allowed=(permission:string)=>permissions.includes(permission);
    const groups=[['Operations',[['Dashboard','/admin','dashboard.view'],['Requests','/admin/inquiries','inquiries.manage'],['Quotations','/admin/quotations','quotations.manage'],['Invoices','/admin/invoices','invoices.manage'],['Payments','/admin/payments','payments.manage']]],['Website',[['Products','/admin/products','products.manage'],['Categories','/admin/categories','products.manage'],['Content pages','/admin/pages','content.manage']]],['Settings',[['Business profile','/admin/business','business.manage'],['Locations','/admin/locations','business.manage'],['Contact channels','/admin/contacts','business.manage'],['Social links','/admin/social-links','business.manage'],['Bank accounts','/admin/bank-accounts','business.manage'],['Administrators','/admin/users','users.manage']]]].map(([label,items]:any)=>[label,items.filter((item:any)=>allowed(item[2]))]).filter(([,items]:any)=>items.length);
    return <div className="admin-theme min-h-screen bg-[#07101f] text-slate-100 lg:grid lg:grid-cols-[260px_1fr]"><aside className="border-r border-white/10 bg-[#050b15] p-6"><BrandLogo /><nav className="mt-10 space-y-7">{groups.map(([label,items]:any) => <div key={label}><p className="mb-3 text-[10px] font-bold uppercase tracking-[.22em] text-slate-600">{label}</p>{items.map(([name,href]:any) => <Link key={href} href={href} className="mb-1 block rounded-lg px-3 py-2 text-sm text-slate-400 hover:bg-white/5 hover:text-cyan-300">{name}</Link>)}</div>)}</nav></aside><main><header className="flex items-center justify-between border-b border-white/10 px-6 py-5 lg:px-10"><div><p className="text-xs uppercase tracking-widest text-cyan-300">ViaTech control center</p><h1 className="text-2xl font-bold">{title}</h1></div><div className="flex items-center gap-4 text-sm text-slate-400"><span>{page.props.auth.user?.name}</span><button onClick={()=>router.post('/logout')} className="rounded-lg border border-white/10 px-4 py-2 hover:border-blue-400/40 hover:text-white">Sign out</button></div></header>{page.props.flash?.success&&<div className="mx-6 mt-6 rounded-xl border border-emerald-400/20 bg-emerald-400/10 p-4 text-emerald-200">{page.props.flash.success}</div>}<div className="p-6 lg:p-10">{children}</div></main></div>;
}
